open Std

type t =
  | ERROR
  | WHITESPACE
  | COMMENT
  | PROGRAM
  | FACT
  | RULE
  | ATOM
  | NEGATED_ATOM
  | BUILTIN
  | VARIABLE
  | CONSTANT
  | WILDCARD
  | STRING_LITERAL
  | INT_LITERAL
  | IDENT
  | DOT
  | COMMA
  | LPAREN
  | RPAREN
  | BANG
  | COLON_DASH
  | GT
  | LT
  | GTEQ
  | LTEQ
  | EQ
  | NOTEQ

let to_string = function
  | ERROR -> "ERROR"
  | WHITESPACE -> "WHITESPACE"
  | COMMENT -> "COMMENT"
  | PROGRAM -> "PROGRAM"
  | FACT -> "FACT"
  | RULE -> "RULE"
  | ATOM -> "ATOM"
  | NEGATED_ATOM -> "NEGATED_ATOM"
  | BUILTIN -> "BUILTIN"
  | VARIABLE -> "VARIABLE"
  | CONSTANT -> "CONSTANT"
  | WILDCARD -> "WILDCARD"
  | STRING_LITERAL -> "STRING_LITERAL"
  | INT_LITERAL -> "INT_LITERAL"
  | IDENT -> "IDENT"
  | DOT -> "DOT"
  | COMMA -> "COMMA"
  | LPAREN -> "LPAREN"
  | RPAREN -> "RPAREN"
  | BANG -> "BANG"
  | COLON_DASH -> "COLON_DASH"
  | GT -> "GT"
  | LT -> "LT"
  | GTEQ -> "GTEQ"
  | LTEQ -> "LTEQ"
  | EQ -> "EQ"
  | NOTEQ -> "NOTEQ"
