[package]
name = "syn"
version = "0.0.15"
description = "Parser, lexer, CST, and diagnostics toolkit"
license = "Apache-2.0"
public = true

[lib]
path = "src/syn.ml"

[[bin]]
name = "syn"
path = "src/main.ml"

[dependencies]
std = { path = "../std" , version = "*"}
tty = { path  ="../tty", version = "*"} 
colors = { path ="../colors", version = "*"}
ceibo = { path = "../ceibo", version = "*" }
