[package]
name = "syn"
version = "0.1.0"

[lib]
path = "src/syn.ml"

[[bin]]
name = "syn"
path = "src/main.ml"

[dependencies]
std = { path = "../std" }
tty = { path  ="../tty"} 
colors = { path ="../colors"}
ceibo = { path = "../ceibo" }
