[package]
name = "syn"
version = "0.1.0"

[dependencies]
std = { path = "../std" }
tty = { path  ="../tty"} 
colors = { path ="../colors"}

[[bin]]
name = "syn"
path = "src/main.ml"

[[bin]]
name = "syn-test"
path = "src/a_test.ml"
