[package]
name = "blink"
version = "0.0.34"
description = "Streaming HTTP client built on Riot actors"
license = "Apache-2.0"
public = true

[lib]
path = "src/blink.ml"

[[bin]]
name = "simple_https"
path = "examples/simple_https.ml"

[[bin]]
name = "test_https_httpbin"
path = "examples/test_https_httpbin.ml"

[[bin]]
name = "managed_client"
path = "examples/managed_client.ml"

[[bin]]
name = "managed_sse"
path = "examples/managed_sse.ml"

[[bin]]
name = "managed_websocket"
path = "examples/managed_websocket.ml"

[dependencies]
std = { path = "../std", version = "*" }
http = { path = "../http", version = "*" }
