[package]
name = "blink"
version = "0.2.0"

[lib]
path = "src/blink.ml"

[dependencies]
std = { path = "../std" }
miniriot = { path = "../miniriot" }
http = { path = "../http" }

[[bin]]
name = "simple_get"
path = "examples/simple_get.ml"

[[bin]]
name = "streaming"
path = "examples/streaming.ml"

[[bin]]
name = "integration_tests"
path = "tests/integration_tests.ml"
