[package]
name = "tusk-store"
version = "0.1.0"

[lib]
path = "src/tusk_store.ml"

[dependencies]
std = "*"
tusk-model = "*"
miniriot = "*"

[[bin]]
name = "store_tests"
path = "tests/store_tests.ml"


