[package]
name = "pretext"
version = "0.0.18"
description = "Tiny Unicode-aware pretty-printing documents"
license = "Apache-2.0"
public = true

[lib]
path = "src/Pretext.ml"

[dependencies]
std = { path = "../std", version = "*" }
