[package]
name = "tusk-cli"
version = "0.0.1"

[lib]
path = "src/tusk_cli.ml"

[[bin]]
name = "tusk"
path = "src/main.ml"

[dependencies]
std = { path = "../std" }
tusk-init = { path = "../tusk-init" }
tusk-executor = { path = "../tusk-executor" }
tusk-model = { path = "../tusk-model" }
tusk-planner = { path = "../tusk-planner" }
tusk-server = { path = "../tusk-server" }
tusk-store = { path = "../tusk-store" }
tusk-toolchain = { path = "../tusk-toolchain" }
tusk-fix = { path = "../tusk-fix" }
