[package]
name = "tusk-cli"
version = "0.0.1"

[[bin]]
name = "tusk-cli"
path = "src/main.ml"

[dependencies]
jsonrpc = { path = "../jsonrpc" }
mcp = { path = "../mcp" }
miniriot = { path = "../miniriot" }
std = { path = "../std" }
tusk-mcp = { path = "../tusk-mcp" }
tusk-client = { path = "../tusk-client" }
tusk-executor = { path = "../tusk-executor" }
tusk-model = { path = "../tusk-model" }
tusk-planner = { path = "../tusk-planner" }
tusk-protocol = { path = "../tusk-protocol" }
tusk-server = { path = "../tusk-server" }
tusk-store = { path = "../tusk-store" }
tusk-toolchain = { path = "../tusk-toolchain" }
