[package]
name = "tusk-cli"
version = "0.0.1"
description = "Command-line interface for the Tusk build system."
license = "Apache-2.0"
public = true

[lib]
path = "src/tusk_cli.ml"

[[bin]]
name = "tusk"
path = "src/main.ml"

[dependencies]
std = { path = "../std", version = "*" }
tusk-init = { path = "../tusk-init", version = "*" }
tusk-executor = { path = "../tusk-executor", version = "*" }
tusk-model = { path = "../tusk-model", version = "*" }
tusk-planner = { path = "../tusk-planner", version = "*" }
tusk-build = { path = "../tusk-build", version = "*" }
tusk-store = { path = "../tusk-store", version = "*" }
tusk-toolchain = { path = "../tusk-toolchain", version = "*" }
tusk-fix = { path = "../tusk-fix", version = "*" }
tusk-fmt = { path = "../tusk-fmt", version = "*" }
tusk-deps = { path = "../tusk-deps", version = "*" }
tusk-publish = { path = "../tusk-publish", version = "*" }
pkgs-ml = { path = "../pkgs-ml", version = "*" }
tty = { path = "../tty", version = "*" }
