[package]
name = "tusk-tests"
version = "0.1.0"

[dependencies]
kernel = { path = "../kernel" }
std = { path = "../std" }
tusk-model = { path = "../tusk-model" }
tusk-toolchain = { path = "../tusk-toolchain" }
tusk-planner = { path = "../tusk-planner" }
tusk-store = { path = "../tusk-store" }
tusk-executor = { path = "../tusk-executor" }
