[package]
name = "gooey"
version = "0.0.41"
description = "Terminal UI primitives"
license = "Apache-2.0"
public = true

[lib]
path = "src/gooey.ml"

[dependencies]
std = { path = "../std", version = "*" }
tty = { path = "../tty", version = "*" }
colors = { path = "../colors", version = "*" }

[[bin]]
name = "gooey_bench"
path = "bench/gooey_bench.ml"
