[package]
name = "colors"
version = "0.0.38"
description = "Color and terminal palette helpers"
license = "Apache-2.0"
public = true

[lib]
path = "src/colors.ml"

[dependencies]
std = { path = "../std" , version = "*"}

[[bin]]
name = "colors_bench"
path = "bench/colors_bench.ml"
