type t =
  | DOCUMENT | PARAGRAPH | HEADING1 | HEADING2 | HEADING3 | HEADING4 | HEADING5 
  | HEADING6 | CODE_BLOCK | FENCED_CODE_BLOCK | BLOCKQUOTE | LIST | LIST_ITEM
  | THEMATIC_BREAK | TEXT | EMPHASIS | STRONG | INLINE_CODE | LINK | IMAGE
  | HARD_BREAK | SOFT_BREAK | HASH | STAR | UNDERSCORE | BACKTICK | DASH | PLUS
  | LEFT_BRACKET | RIGHT_BRACKET | LEFT_PAREN | RIGHT_PAREN | EXCLAMATION
  | LESS_THAN | GREATER_THAN | EQUAL | DIGIT | DOT | SPACE | TAB | BACKSLASH
  | AMPERSAND | PIPE | TILDE | COLON | QUOTE | DOUBLE_QUOTE | NEWLINE
  | TEXT_TOKEN | ESCAPED_CHAR | EOF | ERROR

val to_string : t -> string
