open Std

type t =
  (* Document structure *)
  | DOCUMENT
  | PARAGRAPH
  | HEADING1
  | HEADING2
  | HEADING3
  | HEADING4
  | HEADING5
  | HEADING6
  | CODE_BLOCK
  | FENCED_CODE_BLOCK
  | BLOCKQUOTE
  | LIST
  | LIST_ITEM
  | THEMATIC_BREAK
  (* Inline elements *)
  | TEXT
  | EMPHASIS
  | STRONG
  | INLINE_CODE
  | LINK
  | IMAGE
  | HARD_BREAK
  | SOFT_BREAK
  (* Tokens *)
  | HASH
  | STAR
  | UNDERSCORE
  | BACKTICK
  | DASH
  | PLUS
  | LEFT_BRACKET
  | RIGHT_BRACKET
  | LEFT_PAREN
  | RIGHT_PAREN
  | EXCLAMATION
  | LESS_THAN
  | GREATER_THAN
  | EQUAL
  | DIGIT
  | DOT
  | SPACE
  | TAB
  | BACKSLASH
  | AMPERSAND
  | PIPE
  | TILDE
  | COLON
  | QUOTE
  | DOUBLE_QUOTE
  | NEWLINE
  | TEXT_TOKEN
  | ESCAPED_CHAR
  | EOF
  (* Error *)
  | ERROR

let to_string = function
  | DOCUMENT -> "DOCUMENT"
  | PARAGRAPH -> "PARAGRAPH"
  | HEADING1 -> "HEADING1"
  | HEADING2 -> "HEADING2"
  | HEADING3 -> "HEADING3"
  | HEADING4 -> "HEADING4"
  | HEADING5 -> "HEADING5"
  | HEADING6 -> "HEADING6"
  | CODE_BLOCK -> "CODE_BLOCK"
  | FENCED_CODE_BLOCK -> "FENCED_CODE_BLOCK"
  | BLOCKQUOTE -> "BLOCKQUOTE"
  | LIST -> "LIST"
  | LIST_ITEM -> "LIST_ITEM"
  | THEMATIC_BREAK -> "THEMATIC_BREAK"
  | TEXT -> "TEXT"
  | EMPHASIS -> "EMPHASIS"
  | STRONG -> "STRONG"
  | INLINE_CODE -> "INLINE_CODE"
  | LINK -> "LINK"
  | IMAGE -> "IMAGE"
  | HARD_BREAK -> "HARD_BREAK"
  | SOFT_BREAK -> "SOFT_BREAK"
  | HASH -> "HASH"
  | STAR -> "STAR"
  | UNDERSCORE -> "UNDERSCORE"
  | BACKTICK -> "BACKTICK"
  | DASH -> "DASH"
  | PLUS -> "PLUS"
  | LEFT_BRACKET -> "LEFT_BRACKET"
  | RIGHT_BRACKET -> "RIGHT_BRACKET"
  | LEFT_PAREN -> "LEFT_PAREN"
  | RIGHT_PAREN -> "RIGHT_PAREN"
  | EXCLAMATION -> "EXCLAMATION"
  | LESS_THAN -> "LESS_THAN"
  | GREATER_THAN -> "GREATER_THAN"
  | EQUAL -> "EQUAL"
  | DIGIT -> "DIGIT"
  | DOT -> "DOT"
  | SPACE -> "SPACE"
  | TAB -> "TAB"
  | BACKSLASH -> "BACKSLASH"
  | AMPERSAND -> "AMPERSAND"
  | PIPE -> "PIPE"
  | TILDE -> "TILDE"
  | COLON -> "COLON"
  | QUOTE -> "QUOTE"
  | DOUBLE_QUOTE -> "DOUBLE_QUOTE"
  | NEWLINE -> "NEWLINE"
  | TEXT_TOKEN -> "TEXT_TOKEN"
  | ESCAPED_CHAR -> "ESCAPED_CHAR"
  | EOF -> "EOF"
  | ERROR -> "ERROR"
