[package]
name = "http"
version = "0.0.30"
description = "HTTP protocol parsing and wire types"
license = "Apache-2.0"
public = true

[lib]
path = "src/http.ml"

[dependencies]
std = { path = "../std", version = "*" }
propane = { path = "../propane", version = "*" }
