[package]
name = "raml-wasm"
version = "0.0.33"

[lib]
path = "src/RamlWasm.ml"

[dependencies]
std = "*"
contentstore = { path = "../../packages/contentstore", version = "*" }
raml-core = { path = "../raml-core", version = "*" }
