[package]
name = "raml-core"
version = "0.0.33"

[lib]
path = "src/RamlCore.ml"

[dependencies]
contentstore = { path = "../../packages/contentstore", version = "*" }
kernel = { path = "../../packages/kernel", version = "*" }
std = "*"
syn = { path = "../syn", version = "*" }
typ = { path = "../typ", version = "*" }
