[package]
name = "tty"
version = "0.0.42"
description = "Terminal control and rendering helpers"
license = "Apache-2.0"
public = true

[lib]
path = "src/tty.ml"

[dependencies]
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
