[workspace]
members = [
  "packages/blink",
  "packages/ceibo",
  "packages/colors",
  "packages/datalog",
  "packages/email",
  "packages/grpc",
  "packages/http",
  "packages/jsonrpc",
  "packages/kernel",
  "packages/lol",
  "packages/markdown",
  "packages/mcp",
  "packages/mime",
  "packages/miniriot",
  "packages/minitusk",
  "packages/poneglyph",
  "packages/postgres",
  "packages/protobuf",
  "packages/pubgrub",
  "packages/raml",
  "packages/sqlite",
  "packages/sqltool",
  "packages/sqlx",
  "packages/sqlx_driver",
  "packages/std",
  "packages/suri",
  "packages/syn",
  "packages/toml",
  "packages/tty",
  "packages/tusk",
  "packages/tusk-core",
  "packages/tusk-executor",
  "packages/tusk-model",
  "packages/tusk-ocaml",
  "packages/tusk-planner",
  "packages/tusk-store",
  "packages/tusk_fix",
  "packages/tusk_fmt",
]

[dependencies]
# Shared external dependencies across workspace members
