[workspace]
members = [
  "packages/blink",
  "packages/ceibo",
  "packages/colors",
  "packages/fixme",
  "packages/gooey",
  "packages/hello-foreign",
  "packages/http",
  "packages/jsonrpc",
  "packages/kernel",
  "packages/krasny",
  "packages/mcp",
  "packages/mime",
  "packages/miniriot",
  "packages/minitusk",
  "packages/minttea",
  "packages/postgres",
  "packages/propane",
  "packages/pubgrub",
  "packages/sqlite",
  "packages/sqlx",
  "packages/sqlx-driver",
  "packages/std",
  "packages/suri",
  "packages/swisstable",
  "packages/syn",
  "packages/tty",
  "packages/tusk-cli",
  "packages/tusk-cmd",
  "packages/tusk-eval",
  "packages/tusk-executor",
  "packages/tusk-fix",
  "packages/tusk-fmt",
  "packages/tusk-init",
  "packages/tusk-model",
  "packages/tusk-pm",
  "packages/tusk-planner",
  "packages/tusk-repl",
  "packages/tusk-server",
  "packages/tusk-store",
  "packages/tusk-toolchain",
  "services/registry",
]

[dependencies]
# Shared external dependencies across workspace members

[tusk.fmt]
ignore = [ 
  "fixtures",
  "diagnostics",
  "expected"
]

[tusk.fix]
ignore = [ 
  "fixtures",
  "diagnostics",
  "expected"
]
rules = [
  "no-stdlib", 
  "-class-case-module-names",
]

[profile.debug]
ocamlc_flags = ["-O0"]
