[workspace]
members = [
  "packages/jsonrpc",
  "packages/kernel",
  "packages/mcp",
  "packages/miniriot",
  "packages/minitusk",
  "packages/sandwormsay",
  "packages/syn",
  "packages/std",
  "packages/tusk",
]

[dependencies]
# Shared external dependencies across workspace members
