[package]
name = "fixme"
version = "0.0.34"
description = "Rule-authoring types for riot-fix"
license = "Apache-2.0"
public = true

[lib]
path = "src/fixme.ml"

[dependencies]
std = { path = "../std", version = "*" }
syn = { path = "../syn", version = "*" }
