[package]
name = "tusk-protocol"
version = "0.0.1"

[lib]
path = "src/tusk_protocol.ml"

[dependencies]
jsonrpc = { path = "../jsonrpc" }
std = { path = "../std" }
tusk-model = { path = "../tusk-model" }
tusk-planner = { path = "../tusk-planner" }
tusk-store = { path = "../tusk-store" }
tusk-executor = { path = "../tusk-executor" }
