[package]
name = "tusk-planner"
version = "0.1.0"

[lib]
path = "src/Tusk_planner.ml"

[dependencies]
std = { path = "../std" }
miniriot = { path = "../miniriot" }
tusk-model = { path = "../tusk-model" }
tusk-store = { path = "../tusk-store" }
tusk-toolchain = { path = "../tusk-toolchain" }

[[bin]]
name = "module-scanner-tests"
path = "tests/module_scanner_tests.ml"

[[bin]]
name = "dependency-resolution-tests"
path = "tests/dependency_resolution_tests.ml"

[[bin]]
name = "action-graph-tests"
path = "tests/action_graph_tests.ml"

[[bin]]
name = "package-planning-tests"
path = "tests/package_planning_tests.ml"

[[bin]]
name = "workspace-planning-tests"
path = "tests/workspace_planning_tests.ml"

[[bin]]
name = "debug-graph"
path = "src/debug_graph.ml"
