[package]
name = "tusk-planner"
version = "0.1.0"

[package.lib]
path = "src/Tusk_planner.ml"

[dependencies]
std = "*"
miniriot = "*"
tusk-model = "*"
tusk-toolchain = "*"

[[bin]]
name = "scanner-tests"
path = "tests/scanner_tests.ml"

[[bin]]
name = "planner-tests"
path = "tests/planner_tests.ml"
