[package]
name = "tusk-planner"
version = "0.0.1"
description = "Dependency graph construction and build planning for Tusk."
license = "Apache-2.0"
public = true

[lib]
path = "src/Tusk_planner.ml"

[dependencies]
std = { path = "../std", version = "*" }
tusk-model = { path = "../tusk-model", version = "*" }
tusk-store = { path = "../tusk-store", version = "*" }
tusk-toolchain = { path = "../tusk-toolchain", version = "*" }
