[package]
name = "datalog"
version = "0.1.0"

[dependencies]
std = { path = "../std" }
ceibo = { path = "../ceibo" }
miniriot = { path = "../miniriot" }

[[bin]]
name = "parser_tests"
path = "tests/parser_tests.ml"
