[package]
name = "riot-cmd"
version = "0.0.40"
description = "Shared command registration interfaces"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_cmd.ml"

[dependencies]
std = { path = "../std", version = "*" }
