[package]
name = "std"
version = "0.0.32"
description = "Standard library for Riot"
license = "Apache-2.0"
public = true

[lib]
path = "src/std.ml"

[riot.fix]
rules = [ "-no-stdlib" ]

[riot.fix.provider]
rules = [
  "no-stdlib",
  "prefer-bang-equal-inequality",
  "no-double-list-rev",
  "prefer-iter-over-ignored-map",
  "prefer-list-is-empty",
  "prefer-option-map-over-manual-match",
  "prefer-result-map-over-manual-match",
  "upgrade-test-ctx-callbacks",
]

[dependencies]
kernel = { path = "../kernel", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }

[build-dependencies]
fixme = { path = "../fixme", version = "*" }

[target.macos]
cc_flags = ["-I/opt/homebrew/opt/openssl@3/include"]
ld_flags = ["-L/opt/homebrew/opt/openssl@3/lib", "-lssl", "-lcrypto", "-lz"]

[target.linux]
ld_flags = ["-lssl", "-lcrypto", "-luuid", "-lz"]
