[package]
name = "std"
version = "0.1.0"

[lib]
path = "src/std.ml"

[[bin]]
name = "file_watcher_example"
path = "examples/file_watcher_example.ml"

[[bin]]
name = "test_uri"
path = "examples/test_uri.ml"

[dependencies]
miniriot = { path = "../miniriot" }
kernel = { path = "../kernel" }
