[package]
name = "std"
version = "0.1.0"

[tusk.fix]
rules = [ "-no-stdlib" ]

[tusk.fix.provider]
rules = [ "no-stdlib" ]

[dependencies]
miniriot = { path = "../miniriot" }
kernel = { path = "../kernel" }

[dev-dependencies]
propane = { path = "../propane" }
