[package]
name = "sqlx"
version = "0.0.29"
description = "High-level SQL API"
license = "Apache-2.0"
public = true

[lib]
path = "src/sqlx.ml"

[dependencies]
std = "*"
kernel = "*"
sqlx-driver = "*"

# TODO: Use these for sqltool example when dev-dependencies are implemented
# [dev-dependencies]
# postgres = { path = "../postgres" }
# sqlite = { path = "../sqlite" }
