[package]
name = "sqlx"
version = "0.0.23"
description = "High-level SQL API"
license = "Apache-2.0"
public = true

[lib]
path = "src/sqlx.ml"

[dependencies]
std = { path = "../std", version = "*" }
kernel = { path = "../kernel" , version = "*"}
sqlx-driver = { path = "../sqlx-driver", version = "*" }

# TODO: Use these for sqltool example when dev-dependencies are implemented
# [dev-dependencies]
# postgres = { path = "../postgres" }
# sqlite = { path = "../sqlite" }
