[package]
name = "sqlx"
version = "0.1.0"

[lib]
path = "src/sqlx.ml"

[dependencies]
std = { path = "../std" }
kernel = { path = "../kernel" }
sqlx-driver = { path = "../sqlx-driver" }

# TODO: Use these for sqltool example when dev-dependencies are implemented
# [dev-dependencies]
# postgres = { path = "../postgres" }
# sqlite = { path = "../sqlite" }
