[package]
name = "tusk-server"
version = "0.0.1"

[lib]
path = "src/tusk_server.ml"

[dependencies]
jsonrpc = { path = "../jsonrpc" }
mcp = { path = "../mcp" }
std = { path = "../std" }
tusk-client = { path = "../tusk-client" }
tusk-model = { path = "../tusk-model" }
tusk-protocol = { path = "../tusk-protocol" }
tusk-executor = { path = "../tusk-executor" }
tusk-planner = { path = "../tusk-planner" }
tusk-store = { path = "../tusk-store" }
tusk-toolchain = { path = "../tusk-toolchain" }
