[package]
name = "riot-executor"
version = "0.0.17"
description = "Build execution and result aggregation"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_executor.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
riot-planner = { path = "../riot-planner", version = "*" }
riot-toolchain = { path = "../riot-toolchain", version = "*" }
riot-store = { path = "../riot-store", version = "*" }

[dev-dependencies]
pkgs-ml = { path = "../pkgs-ml", version = "*" }
riot-deps = { path = "../riot-deps", version = "*" }
