[package]
name = "riot-executor"
version = "0.0.11"
description = "Build execution and result aggregation"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_executor.ml"

[dependencies]
std = { path = "../riot-planner", version = "*" }
riot-model = { path = "../riot-planner", version = "*" }
riot-planner = { path = "../riot-planner", version = "*" }
riot-toolchain = { path = "../riot-planner", version = "*" }
riot-store = { path = "../riot-planner", version = "*" }
