[package]
name = "sqlx-driver"
version = "0.0.37"
description = "Database driver interface for sqlx"
license = "Apache-2.0"
public = true

[lib]
path = "./src/sqlx_driver.ml"

[dependencies]
std = { path = "../std", version = "*" }
serde = { path = "../serde", version = "*" }
