[package]
name = "sqlx-driver"
version = "0.0.1"
description = "Shared database driver interface for sqlx adapters."
license = "Apache-2.0"

[lib]
path = "./src/sqlx_driver.ml"

[dependencies]
std = { path = "../std", version = "*" }
# Add dependencies here
