[package]
name = "pkgs-ml"
version = "0.0.38"
description = "pkgs.ml registry client and cache helpers"
license = "Apache-2.0"
public = true

[lib]
path = "src/pkgs_ml.ml"

[[bin]]
name = "pkgs_ml_tests"
path = "tests/pkgs_ml_tests.ml"


[dependencies]
std = { path = "../std", version = "*" }
blink = { path = "../blink", version = "*" }
