[package]
name = "poneglyph"
version = "0.1.0"

[lib]
path = "src/poneglyph.ml"

[[bin]]
name = "poneglyph"
path = "src/main.ml"

[[bin]]
name = "poneglyph_core_ops_bench"
path = "examples/core_ops_bench.ml"

[[bin]]
name = "poneglyph_query_bench"
path = "examples/query_bench.ml"

[[bin]]
name = "poneglyph_lsm_bench"
path = "examples/lsm_bench.ml"

[[bin]]
name = "poneglyph_lsm_backend_bench"
path = "examples/lsm_backend_bench.ml"

[[bin]]
name = "poneglyph_backend_comparison_bench"
path = "examples/backend_comparison_bench.ml"

[dependencies]
std = { path = "../std" }
datalog = { path = "../datalog" }
propane = { path = "../propane" }
