[package]
name = "minitusk"
version = "0.0.1"
description = "Bootstrap build tool for building the Tusk toolchain."
license = "Apache-2.0"
public = true

[tusk.fix]
rules = [ 
  "-no-stdlib" 
]

[dependencies]
stdlib = "*"
unix = "*"
# Only needs standard library
