[package]
name = "tusk-toolchain"
version = "0.1.0"

[package.lib]
path = "src/tusk_toolchain.ml"

[dependencies]
std = "*"
miniriot = "*"
tusk-model = "*"

[[bin]]
name = "toolchain-tests"
path = "tests/toolchain_tests.ml"
