[package]
name = "tusk-toolchain"
version = "0.0.1"
description = "Compiler and toolchain invocation wrappers for Tusk."
license = "Apache-2.0"
public = true

[lib]
path = "src/tusk_toolchain.ml"

[dependencies]
std = "*"
tusk-model = "*"
