open Std

let materialize = fun (config: Context.t) ->
  let content =
    if config.is_library then
      {|# Generated by `riot init`
FROM ghcr.io/leostera/riot/riot-builder:latest

WORKDIR /app

COPY . /app

RUN riot build --release
RUN riot test
|}
    else {|# Generated by `riot init`
FROM ghcr.io/leostera/riot/riot-builder:latest AS build

WORKDIR /app

COPY . /app

RUN riot build --release |} ^ config.workspace_name ^ {|
RUN riot test

FROM alpine:latest

RUN apk add --no-cache \
    libgcc \
    libstdc++ \
    ca-certificates

COPY --from=build /app/_build/release/*/|} ^ config.package_name ^ {| /usr/local/bin/|} ^ config.package_name ^ {|

RUN addgroup -g 1000 riot && \
    adduser -D -u 1000 -G riot riot

USER riot

ENTRYPOINT ["/usr/local/bin/|} ^ config.package_name ^ {|"]
CMD ["--help"]
|}
  in
  Writer.write_file config ~relative_path:"Dockerfile" ~content ~executable:false
