[package]
name = "sqlite"
version = "0.0.43"
description = "SQLite adapter for sqlx"
license = "Apache-2.0"
public = true

[lib]
path = "src/sqlite.ml"

[riot.fix]
rules = [
  "-prefer-sequences-over-let-unit",
]

[dependencies]
std = { path = "../std", version = "*" }
sqlx-driver = { path = "../sqlx-driver", version = "*" }
serde = { path = "../serde", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
sqlx = { path = "../sqlx", version = "*" }

[target.macos]
ld_flags = ["-lsqlite3"]

[target.linux]
ld_flags = ["-lsqlite3"]

[[bin]]
name = "sqlite_tests"
path = "tests/sqlite_tests.ml"

[[bin]]
name = "sqlite_property_tests"
path = "tests/property_tests.ml"

[[bin]]
name = "sqlite_fuzz_tests"
path = "tests/fuzz_tests.ml"
