[package]
name = "sqlite"
version = "0.0.30"
description = "SQLite adapter for sqlx"
license = "Apache-2.0"
public = true

[lib]
path = "src/sqlite.ml"

[dependencies]
std = { path = "../std", version = "*" }
sqlx-driver = { path = "../sqlx-driver", version = "*" }
# Add dependencies here
