[package]
name = "sqlite"
version = "0.1.0"
description = "SQLite adapter for the sqlx database APIs."
license = "Apache-2.0"
public = true

[lib]
path = "src/sqlite.ml"

[dependencies]
std = { path = "../std" }
sqlx-driver = { path = "../sqlx-driver" }
# Add dependencies here

