open Std
open Std.Collections
open Riot_model

let template = fun (modules: Module.t list) ->
  let header = "(* Alias module generated by riot *)" in
  let unique_modules =
    modules
    |> List.filter_map ~fn:(fun mod_ ->
      match Module.kind mod_ with
      | `interface -> None
      | `implementation ->
          let name = Module.module_name mod_ |> Module_name.to_string in
          let ns = Module.namespaced_name mod_ in
          Some (name, ns))
    |> List.sort ~compare:(fun (n1, _) (n2, _) ->
      String.compare n1 n2)
    |> List.unique ~compare:(fun (n1, _) (n2, _) ->
      String.compare n1 n2)
  in
  let body =
    List.map unique_modules ~fn:(fun (name, ns) -> "module " ^ name ^ " = " ^ ns)
  in
  let super_body =
    if List.is_empty unique_modules then
      []
    else
      [ ""; "module Super = struct" ] @ body @ [ "end" ]
  in
  String.concat "\n" (header :: body @ super_body)

let make_node = fun (ns: Namespace.t) (modules: Module.t list) ->
  let ns_prefix = Namespace.to_string ns in
  let filename =
    if ns_prefix = "" then
      "Aliases.ml-gen"
    else
      ns_prefix ^ "__Aliases.ml-gen"
  in
  let path = Path.v filename in
  let mod_ = Module.make ~namespace:Namespace.empty ~filename:path in
  let file = Module_node.Generated { path; contents = template modules } in
  let kind = Module_node.ML mod_ in
  { Module_node.file; open_modules = []; kind }
