open Std
open Std.Collections
open Riot_model

module G = Std.Graph.SimpleGraph

let template = fun (children: Module.t list) ->
  let header = "(* Library interface module generated by riot *)" in
  let unique_modules = children |> List.map ~fn:(
    fun mod_ ->
      let simple_name = Module.module_name mod_ |> Module_name.to_string in
      let qualified_name = Module.qualified_name mod_ in (simple_name, qualified_name)
  ) |> List.sort ~compare:(
    fun (a, _) (b, _) -> String.compare a b
  ) |> List.unique ~compare:(
    fun (a, _) (b, _) -> String.compare a b
  ) in
  let body = List.map unique_modules ~fn:(
    fun (simple, qualified) -> "module " ^ simple ^ " = " ^ qualified
  ) in String.concat "\n" (header :: body)

let make_node = fun (lib: Module.t) (children: Module.t list) aliases ~exists ~actual_path ->
  let path =
    match actual_path with
    | Some p -> p
    | None -> Module.filename lib
  in
  let file =
    if exists then
      Module_node.Concrete path
    else Module_node.Generated { path; contents = template children }
  in
  let kind =
    match Module.kind lib with
    | `interface -> Module_node.MLI lib
    | `implementation -> Module_node.ML lib
  in
  let open_modules = aliases in { Module_node.file; open_modules; kind }
