[package]
name = "contentstore"
version = "0.0.35"
description = "Generic content-addressable storage primitives"
license = "Apache-2.0"
public = true

[lib]
path = "src/contentstore.ml"

[dependencies]
std = "*"

[dev-dependencies]
propane = { path = "../propane", version = "*" }
