[package]
name = "riot-fmt"
version = "0.0.30"
description = "Formatting checks around Krasny"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_fmt.ml"

[[bin]]
name = "fmt_tests"
path = "tests/fmt_tests.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
krasny = { path = "../krasny", version = "*" }
syn = { path = "../syn", version = "*" }
