[package]
name = "markdown"
version = "0.0.42"

[lib]
path = "src/Markdown.ml"

[[bin]]
name = "spec_fixtures_tests"
path = "tests/spec_fixtures_test.ml"

[[bin]]
name = "incremental_tests"
path = "tests/incremental_tests.ml"

[[bin]]
name = "markdown_bench"
path = "bench/markdown_bench.ml"


[dependencies]
std = "*"
