import type { APIRoute } from "astro";

const body = [
  "# pkgs.ml",
  "",
  "pkgs.ml is Riot's OCaml package registry.",
  "",
  "Public surfaces:",
  "- Human website: https://pkgs.ml",
  "- Control-plane API: https://api.pkgs.ml",
  "- CDN/index/download surface: https://cdn.pkgs.ml",
  "",
  "Preferred registry client flow:",
  "1. Fetch https://cdn.pkgs.ml/index/v1/config.json",
  "2. Read package shard documents from the sparse index",
  "3. Download artifacts by joining artifact_base_url and source_key",
  "4. Use https://api.pkgs.ml/v1/search for free-text search",
  "5. Use https://api.pkgs.ml/v1/publish to publish package-root tar.gz artifacts",
  "",
  "Important API routes:",
  "- GET https://api.pkgs.ml/",
  "- GET https://api.pkgs.ml/v1/search?q=<query>",
  "- POST https://api.pkgs.ml/v1/publish",
  "- GET https://api.pkgs.ml/v1/views/packages/<package>/overview",
  "- GET https://api.pkgs.ml/v1/views/packages/<package>/downloads",
  "- GET https://api.pkgs.ml/v1/views/packages/<package>/relations",
  "- GET https://api.pkgs.ml/v1/packages/<package>/events?limit=<count>",
  "- GET https://api.pkgs.ml/v1/views/stats/summary",
  "- GET https://api.pkgs.ml/v1/views/stats/dashboard",
  "",
  "Publishing contract:",
  "- Authenticate with a publish token from pkgs.ml",
  "- Send Authorization: Bearer <token>",
  "- Send Content-Type: application/gzip",
  "- Body must be a package-root tar.gz",
  "- The archive must contain tusk.toml at archive root",
  "",
  "Sparse index contract:",
  "- Fetch index config from cdn.pkgs.ml/index/v1/config.json",
  "- Read package documents from cdn.pkgs.ml/index/v1/<sharded-package>.json",
  "- source_key identifies the published install artifact",
  "- artifact_base_url currently points at https://cdn.pkgs.ml",
  "",
  "Privacy and telemetry:",
  "- pkgs.ml does not intentionally store raw IP addresses in the registry database",
  "- pkgs.ml does not keep generic per-request logs as a product feature",
  "- pkgs.ml records purpose-built facts such as package downloads, Riot downloads, OCaml downloads, index reads, and package lifecycle events",
  "",
  "Human-oriented docs:",
  "- API overview: https://pkgs.ml/api",
  "- Privacy notice: https://pkgs.ml/privacy",
  "- Stats dashboard: https://pkgs.ml/stats",
  "- Live registry activity: https://pkgs.ml/activity",
].join("\n");

export const GET: APIRoute = async () => {
  return new Response(body, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "public, max-age=300",
    },
  });
};
