[package]
name = "serde"
version = "0.0.35"
description = "Type-safe serialization framework for Riot"
public = true
license = "Apache-2.0"

[lib]
path = "src/serde.ml"

[dependencies]
std = "*"
# Add dependencies here
