[package]
name = "raml-core"
version = "0.0.33"

[lib]
path = "src/RamlCore.ml"

[dependencies]
contentstore = { path = "../../packages/contentstore", version = "*" }
std = "*"
syn = { path = "../../packages/syn", version = "*" }
typ = { path = "../../packages/typ", version = "*" }
