[package]
name = "riot-cli"
version = "0.0.32"
description = "Command-line interface for Riot"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_cli.ml"

[[bin]]
name = "riot"
path = "src/main.ml"

[dependencies]
std = { path = "../std", version = "*" }
jollyroger = { path = "../jollyroger", version = "*" }
riot-init = { path = "../riot-init", version = "*" }
riot-run = { path = "../riot-run", version = "*" }
riot-install = { path = "../riot-install", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
riot-planner = { path = "../riot-planner", version = "*" }
riot-build = { path = "../riot-build", version = "*" }
riot-test = { path = "../riot-test", version = "*" }
riot-store = { path = "../riot-store", version = "*" }
riot-bench = { path = "../riot-bench", version = "*" }
riot-fuzz = { path = "../riot-fuzz", version = "*" }
riot-toolchain = { path = "../riot-toolchain", version = "*" }
riot-fix = { path = "../riot-fix", version = "*" }
riot-fmt = { path = "../riot-fmt", version = "*" }
riot-lsp = { path = "../riot-lsp", version = "*" }
riot-doc = { path = "../riot-doc", version = "*" }
riot-deps = { path = "../riot-deps", version = "*" }
riot-publish = { path = "../riot-publish", version = "*" }
pkgs-ml = { path = "../pkgs-ml", version = "*" }
tty = { path = "../tty", version = "*" }
contentstore = { path = "../contentstore", version = "*" }
