[package]
name = "serde-json"
version = "0.0.17"

[lib]
path = "src/serde_json.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*"}

[dev-dependencies]
propane = { path = "../propane", version = "*" }
