[package]
name = "serde-json"
version = "0.0.36"
description = "JSON support for the Serde serialization framework"
public = true
license = "Apache-2.0"

[lib]
path = "src/serde_json.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*"}

[dev-dependencies]
propane = { path = "../propane", version = "*" }
