[package]
name = "suri"

[dependencies]
std = { path = "../std" }
miniriot = { path = "../miniriot" }
http = { path = "../http" }
blink = { path = "../blink" }

[[bin]]
name = "integration_tests"
path = "tests/integration_tests.ml"
