[package]
name = "suri"

[lib]
path = "src/suri.ml"

[dependencies]
std = { path = "../std" }
http = { path = "../http" }
blink = { path = "../blink" }
tusk-model = { path = "../tusk-model" }

# NOTE: Disabled until Telemetry.event API is updated
# [[command]]
# name = "suri"
# help = "Suri web framework commands"
# path = "src/tusk_cmd/main.ml"
