[package]
name = "suri"
version = "0.1.0"
description = "Web framework, middleware, and routing for Riot applications."
license = "Apache-2.0"
public = true

[lib]
path = "src/suri.ml"

[dependencies]
std = { path = "../std" }
http = { path = "../http" }
blink = { path = "../blink" }
tusk-model = { path = "../tusk-model" }

# NOTE: Disabled until Telemetry.event API is updated
# [[command]]
# name = "suri"
# help = "Suri web framework commands"
# path = "src/tusk_cmd/main.ml"
