[package]
name = "riot-build"
version = "0.0.40"
description = "In-process build session runtime"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_build.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
riot-deps = { path = "../riot-deps", version = "*" }
pkgs-ml = { path = "../pkgs-ml", version = "*" }
riot-planner = { path = "../riot-planner", version = "*" }
riot-store = { path = "../riot-store", version = "*" }
riot-toolchain = { path = "../riot-toolchain", version = "*" }
