[package]
name = "riot-build2"
version = "0.0.39"
description = "Incremental graph execution engine rewrite prototype"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_build2.ml"

[dependencies]
std = "*"
riot-model = "*"
riot-planner = "*"
riot-store = "*"
riot-toolchain = "*"
serde = "*"
serde-json = "*"
