[package]
name = "riot-deps"
version = "0.0.30"
description = "Dependency management and lock refresh"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_deps.ml"

[[bin]]
name = "pm_tests"
path = "tests/pm_tests.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
pkgs-ml = { path = "../pkgs-ml", version = "*" }
pubgrub = { path = "../pubgrub", version = "*" }
riot-fmt = { path = "../riot-fmt", version = "*" }
riot-fix = { path = "../riot-fix", version = "*" }
riot-planner = { path = "../riot-planner", version = "*" }
riot-store = { path = "../riot-store", version = "*" }
riot-toolchain = { path = "../riot-toolchain", version = "*" }
