use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let fixture_root = manifest_dir.join("tests/fixtures");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", fixture_root.display());

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs\n");
    generated.push_str("mod generated_fixture_tests {\n");
    generated.push_str("    use super::*;\n\n");

    emit_fixture_tests(
        &mut generated,
        "program",
        "program_fixture_compiles",
        &fixture_root,
        &fixture_root.join("programs"),
    )
    .expect("generate program fixture tests");

    emit_fixture_tests(
        &mut generated,
        "diagnostic",
        "diagnostic_fixture_fails",
        &fixture_root,
        &fixture_root.join("diagnostics"),
    )
    .expect("generate diagnostic fixture tests");

    generated.push_str("}\n");

    fs::write(out_dir.join("fixture_tests.rs"), generated).expect("write fixture test module");
}

fn emit_fixture_tests(
    generated: &mut String,
    kind: &str,
    runner: &str,
    fixture_root: &Path,
    root: &Path,
) -> io::Result<()> {
    let mut fixtures = Vec::new();
    collect_ml_fixtures(root, &mut fixtures)?;
    fixtures.sort();

    if fixtures.is_empty() {
        panic!(
            "expected at least one {kind} fixture under {}",
            root.display()
        );
    }

    let mut names = BTreeSet::new();
    for fixture in fixtures {
        let relative = fixture
            .strip_prefix(fixture_root)
            .expect("fixture lives under fixture root");
        let test_name = unique_test_name(kind, relative, &mut names);
        let fixture_path = format!("tests/fixtures/{}", slash_path(relative));

        generated.push_str("    #[test]\n");
        generated.push_str("    fn ");
        generated.push_str(&test_name);
        generated.push_str("() -> FixtureResult {\n");
        generated.push_str("        ");
        generated.push_str(runner);
        generated.push_str("(Path::new(");
        generated.push_str(&format!("{fixture_path:?}"));
        generated.push_str("))\n");
        generated.push_str("    }\n\n");
    }

    Ok(())
}

fn collect_ml_fixtures(root: &Path, fixtures: &mut Vec<PathBuf>) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", root.display());

    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            collect_ml_fixtures(&path, fixtures)?;
        } else if file_type.is_file() && path.extension().is_some_and(|extension| extension == "ml")
        {
            println!("cargo:rerun-if-changed={}", path.display());
            fixtures.push(path);
        }
    }

    Ok(())
}

fn unique_test_name(kind: &str, fixture: &Path, names: &mut BTreeSet<String>) -> String {
    let mut name = sanitize_identifier(&format!("{kind}_{}", slash_path(fixture)));
    if name.ends_with("_ml") {
        name.truncate(name.len() - 3);
    }

    let base = name.clone();
    let mut index = 2;
    while !names.insert(name.clone()) {
        name = format!("{base}_{index}");
        index += 1;
    }
    name
}

fn sanitize_identifier(input: &str) -> String {
    let mut output = String::new();

    for ch in input.chars() {
        match ch {
            'a'..='z' | 'A'..='Z' | '0'..='9' => output.push(ch),
            _ => output.push('_'),
        }
    }

    if output.chars().next().is_none_or(|ch| ch.is_ascii_digit()) {
        output.insert(0, '_');
    }

    output
}

fn slash_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}
