name = "riot-get"
main = "src/main.ts"
compatibility_date = "2026-04-02"
workers_dev = false

[vars]
RIOT_INSTALL_SCRIPT_URL = "https://cdn.pkgs.ml/riot/install.sh"

[[routes]]
pattern = "get.riot.ml"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
