[package]
name = "tusk"
version = "0.0.1"

[[bin]]
name = "tusk"
path = "main.ml"

[dependencies]
miniriot = { path = "../miniriot" }
sexp = { path = "../sexp" }
toml = { path = "../toml" }
json = { path = "../json" }
unix = "*"
