[package]
name = "tusk"
version = "0.0.1"

[[bin]]
name = "tusk"
path = "src/main.ml"

[dependencies]
json = { path = "../json" }
jsonrpc = { path = "../jsonrpc" }
mcp = { path = "../mcp" }
miniriot = { path = "../miniriot" }
sexp = { path = "../sexp" }
std = { path = "../std" }
toml = { path = "../toml" }
