[package]
name = "ceibo"
version = "0.0.16"
description = "Red-green syntax trees for incremental parsers"
license = "Apache-2.0"
public = true

[lib]
path = "src/ceibo.ml"

[dependencies]
std = { path = "../std", version = "*" }
