open Std
open Tusk_model

let template (modules : Module.t list) =
  let header = "(* Alias module generated by tusk *)" in
  let unique_modules =
    modules
    |> List.filter_map (fun mod_ ->
        match Module.kind mod_ with
        | `interface -> None
        | `implementation ->
            let name = Module.module_name mod_ |> Module_name.to_string in
            let ns = Module.namespaced_name mod_ in
            Some (name, ns))
    |> List.sort_uniq (fun (n1, _) (n2, _) -> String.compare n1 n2)
  in
  let body =
    List.map (fun (name, ns) -> format "module %s = %s" name ns) unique_modules
  in
  String.concat "\n" (header :: body)

let make_node (ns : Namespace.t) (modules : Module.t list) =
  let ns_prefix = Namespace.to_string ns in
  let filename =
    if ns_prefix = "" then "Aliases.ml-gen" else ns_prefix ^ "__Aliases.ml-gen"
  in
  let path = Path.v filename in
  let mod_ = Module.make ~namespace:Namespace.empty ~filename:path in
  let file = Module_node.Generated { path; contents = template modules } in
  let kind = Module_node.ML mod_ in
  { Module_node.file; open_modules = []; kind }
