open Std
open Tusk_model
module G = Std.Graph.SimpleGraph

let template (children : Module.t list) =
  let header = "(* Library interface module generated by tusk *)" in
  let unique_modules =
    children
    |> List.map (fun mod_ ->
        let simple_name = Module.module_name mod_ |> Module_name.to_string in
        let qualified_name = Module.qualified_name mod_ in
        (simple_name, qualified_name))
    |> List.sort_uniq (fun (a, _) (b, _) -> String.compare a b)
  in
  let body =
    List.map
      (fun (simple, qualified) -> format "module %s = %s" simple qualified)
      unique_modules
  in
  String.concat "\n" (header :: body)

let make_node (lib : Module.t) (children : Module.t list) aliases ~exists
    ~actual_path =
  let path =
    match actual_path with Some p -> p | None -> Module.filename lib
  in
  let file =
    if exists then Module_node.Concrete path
    else Module_node.Generated { path; contents = template children }
  in
  let kind =
    match Module.kind lib with
    | `interface -> Module_node.MLI lib
    | `implementation -> Module_node.ML lib
  in
  let open_modules = aliases in
  { Module_node.file; open_modules; kind }
