[package]
name = "tusk-fix"
version = "0.1.0"

[lib]
path = "src/tusk_fix.ml"

[[bin]]
name = "tusk-fix"
path = "src/main.ml"

[dependencies]
std = { path = "../std" }
syn = { path = "../syn" }
tusk-model = { path = "../tusk-model" }

[[bin]]
name = "fix_tests"
path = "tests/fix_tests.ml"

[[bin]]
name = "runner_tests"
path = "tests/runner_tests.ml"
