[package]
name = "lsp"
version = "0.0.36"
description = "Language Server Protocol types and codecs"
license = "Apache-2.0"
public = true

[lib]
path = "src/lsp.ml"

[dependencies]
std = { path = "../std", version = "*" }
jsonrpc = { path = "../jsonrpc", version = "*" }
