use anyhow::Result;
use crate::types::*;

pub struct OCamlGenerator {
    module_name: String,
}

impl OCamlGenerator {
    pub fn new(module_name: String) -> Self {
        Self { module_name }
    }
    
    pub fn module_name(&self) -> &str {
        &self.module_name
    }
    
    pub fn generate(&self, bindings: &Bindings) -> Result<String> {
        let mut code = String::new();
        
        code.push_str(&format!("(* Generated by riot-bindgen for {} *)\n\n", self.module_name));
        
        if !bindings.types.is_empty() {
            code.push_str("(* Types *)\n\n");
            for ty in &bindings.types {
                code.push_str(&self.generate_type(ty));
                code.push_str("\n\n");
            }
        }
        
        if !bindings.functions.is_empty() {
            code.push_str("(* Functions *)\n\n");
            for func in &bindings.functions {
                code.push_str(&self.generate_function(func));
                code.push_str("\n\n");
            }
        }
        
        Ok(code)
    }
    
    pub fn generate_interface(&self, bindings: &Bindings) -> Result<String> {
        let mut code = String::new();
        
        code.push_str(&format!("(* Generated interface for {} *)\n\n", self.module_name));
        
        if !bindings.types.is_empty() {
            for ty in &bindings.types {
                code.push_str(&self.generate_type_sig(ty));
                code.push_str("\n\n");
            }
        }
        
        if !bindings.functions.is_empty() {
            for func in &bindings.functions {
                code.push_str(&self.generate_function_sig(func));
                code.push_str("\n\n");
            }
        }
        
        Ok(code)
    }
    
    fn generate_type(&self, ty: &TypeDef) -> String {
        let mut code = String::new();
        
        if let Some(docs) = &ty.docs {
            for line in docs.lines() {
                code.push_str(&format!("(** {} *)\n", line));
            }
        }
        
        match &ty.kind {
            TypeKind::Struct { fields } => {
                code.push_str(&format!("type {} = {{\n", ty.name));
                for field in fields {
                    if let Some(doc) = &field.docs {
                        code.push_str(&format!("  (** {} *)\n", doc));
                    }
                    code.push_str(&format!("  {} : {};\n", field.name, field.ty.to_ocaml()));
                }
                code.push_str("}");
            }
            TypeKind::Enum { variants } => {
                code.push_str(&format!("type {} =\n", ty.name));
                for (i, variant) in variants.iter().enumerate() {
                    let sep = if i == 0 { "  " } else { "| " };
                    
                    if let Some(doc) = &variant.docs {
                        code.push_str(&format!("  (** {} *)\n", doc));
                    }
                    
                    if variant.fields.is_empty() {
                        code.push_str(&format!("  {}{}\n", sep, variant.name));
                    } else {
                        let fields = variant.fields.iter()
                            .map(|f| f.to_ocaml())
                            .collect::<Vec<_>>()
                            .join(" * ");
                        code.push_str(&format!("  {}{} of {}\n", sep, variant.name, fields));
                    }
                }
            }
            TypeKind::Alias { target } => {
                code.push_str(&format!("type {} = {}", ty.name, target.to_ocaml()));
            }
        }
        
        code
    }
    
    fn generate_type_sig(&self, ty: &TypeDef) -> String {
        let mut code = String::new();
        
        if let Some(docs) = &ty.docs {
            for line in docs.lines() {
                code.push_str(&format!("(** {} *)\n", line));
            }
        }
        
        match &ty.kind {
            TypeKind::Struct { fields } => {
                code.push_str(&format!("type {} = {{\n", ty.name));
                for field in fields {
                    code.push_str(&format!("  {} : {};\n", field.name, field.ty.to_ocaml()));
                }
                code.push_str("}");
            }
            TypeKind::Enum { variants } => {
                code.push_str(&format!("type {} =\n", ty.name));
                for (i, variant) in variants.iter().enumerate() {
                    let sep = if i == 0 { "  " } else { "| " };
                    if variant.fields.is_empty() {
                        code.push_str(&format!("  {}{}\n", sep, variant.name));
                    } else {
                        let fields = variant.fields.iter()
                            .map(|f| f.to_ocaml())
                            .collect::<Vec<_>>()
                            .join(" * ");
                        code.push_str(&format!("  {}{} of {}\n", sep, variant.name, fields));
                    }
                }
            }
            TypeKind::Alias { target } => {
                code.push_str(&format!("type {} = {}", ty.name, target.to_ocaml()));
            }
        }
        
        code
    }
    
    fn generate_function(&self, func: &Function) -> String {
        let mut code = String::new();
        
        if let Some(docs) = &func.docs {
            for line in docs.lines() {
                code.push_str(&format!("(** {} *)\n", line));
            }
        }
        
        code.push_str(&format!("external {} : ", func.name));
        
        if func.params.is_empty() {
            code.push_str("unit");
        } else {
            for (i, param) in func.params.iter().enumerate() {
                if i > 0 {
                    code.push_str(" -> ");
                }
                code.push_str(&param.ty.to_ocaml());
            }
        }
        
        code.push_str(" -> ");
        code.push_str(&func.return_type.to_ocaml());
        code.push_str(&format!(" = \"rust_{}\"\n", func.rust_name));
        
        code
    }
    
    fn generate_function_sig(&self, func: &Function) -> String {
        let mut code = String::new();
        
        if let Some(docs) = &func.docs {
            for line in docs.lines() {
                code.push_str(&format!("(** {} *)\n", line));
            }
        }
        
        code.push_str(&format!("val {} : ", func.name));
        
        if func.params.is_empty() {
            code.push_str("unit");
        } else {
            for (i, param) in func.params.iter().enumerate() {
                if i > 0 {
                    code.push_str(" -> ");
                }
                code.push_str(&param.ty.to_ocaml());
            }
        }
        
        code.push_str(" -> ");
        code.push_str(&func.return_type.to_ocaml());
        
        code
    }
}
