[package]
name = "riot-run"
version = "0.0.38"
description = "Run command orchestration on top of riot-build"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_run.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-build = { path = "../riot-build", version = "*" }
riot-deps = { path = "../riot-deps", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
riot-store = { path = "../riot-store", version = "*" }
