[package]
name = "tusk-mcp"
version = "0.0.1"

[lib]
path = "src/tusk_mcp.ml"

[dependencies]
jsonrpc = { path = "../jsonrpc" }
mcp = { path = "../mcp" }
miniriot = { path = "../miniriot" }
std = { path = "../std" }
tusk-client = { path = "../tusk-client" }
tusk-model = { path = "../tusk-model" }
tusk-protocol = { path = "../tusk-protocol" }
tusk-server = { path = "../tusk-server" }
