(** Module Graph - Intra-package dependency graph for building a single package

    This is a port of minitusk's dep_graph.ml with full support for:
    - Namespacing
    - Directory-based libraries
    - Recursive sublibraries
    - Generated library interface modules
    - Alias files *)

open Std
open Model
open Ocaml

module G = Graph.SimpleGraph
(** Use Std.Graph for graph operations *)

(** Graph node representing a module or file to compile *)
type kind = ML of Module.t | MLI of Module.t | C | H | Other of string | Root

type file =
  | Concrete of Path.t
  | Generated of { path : Path.t; contents : string }

let file_to_string file =
  match file with
  | Concrete path -> Path.to_string path
  | Generated { path; _ } -> Path.to_string path ^ " (generated)"

type dep = { file : file; mutable open_modules : dep G.node list; kind : kind }

type t = {
  package : Workspace.package;
  toolchain : Toolchains.toolchain;
  namespace : Namespace.t;
  workspace : Workspace.t;
  graph : dep G.t;
  registry : Module_registry.t;
}
(** The module graph structure *)

type error = string

let root_node = { file = Concrete (Path.v ""); open_modules = []; kind = Root }

module Alias_module = struct
  let template (modules : Module.t list) =
    let header = "(* Alias module generated by tusk *)" in
    let unique_modules =
      modules
      |> List.filter_map (fun mod_ ->
          match Module.kind mod_ with
          | `interface -> None
          | `implementation ->
              let name = Module.module_name mod_ |> Module_name.to_string in
              let ns = Module.namespaced_name mod_ in
              Some (name, ns))
      |> List.sort_uniq (fun (n1, _) (n2, _) -> String.compare n1 n2)
    in
    let body =
      List.map
        (fun (name, ns) -> Printf.sprintf "module %s = %s" name ns)
        unique_modules
    in
    String.concat "\n" (header :: body)

  let make_node (ns : Namespace.t) (modules : Module.t list) =
    let ns_prefix = Namespace.to_string ns in
    let filename =
      if ns_prefix = "" then "Aliases.ml.gen"
      else ns_prefix ^ "__Aliases.ml.gen"
    in
    let path = Path.v filename in
    let mod_ = Module.make ~namespace:ns ~filename:path in
    let file = Generated { path; contents = template modules } in
    let kind = ML mod_ in
    { file; open_modules = []; kind }
end

module Library_interface = struct
  let template (children : Module.t list) =
    let header = "(* Library interface module generated by tusk *)" in
    let unique_names =
      children
      |> List.map (fun mod_ -> Module.module_name mod_ |> Module_name.to_string)
      |> List.sort_uniq String.compare
    in
    let body =
      List.map
        (fun name -> Printf.sprintf "module %s = %s" name name)
        unique_names
    in
    String.concat "\n" (header :: body)

  let make_node (lib : Module.t) (children : Module.t list) aliases ~exists
      ~actual_path =
    let path =
      match actual_path with Some p -> p | None -> Module.filename lib
    in
    let file =
      if exists then Concrete path
      else Generated { path; contents = template children }
    in
    let kind =
      match Module.kind lib with
      | `interface -> MLI lib
      | `implementation -> ML lib
    in
    let open_modules = aliases in
    { file; open_modules; kind }
end

module Ocaml_module = struct
  let make_node (mod_ : Module.t) aliases =
    let path = Module.filename mod_ in
    let file = Concrete path in
    let kind =
      match Module.kind mod_ with
      | `interface -> MLI mod_
      | `implementation -> ML mod_
    in
    let open_modules = aliases in
    { file; open_modules; kind }
end

type scan_ctx = {
  ns : Namespace.t;
  parent_intf : dep G.node;
  parent_impl : dep G.node;
  aliases : dep G.node list;
}

(** Create a new module graph for a package *)
let create ~node:(build_node : Build_node.t) ~workspace =
  let package = build_node.package in
  let toolchain = build_node.toolchain in
  let namespace = Namespace.of_list [ String.capitalize_ascii package.name ] in

  {
    package;
    toolchain;
    namespace;
    workspace;
    graph = G.make ();
    registry = Module_registry.create ();
  }

(** Scan directory tree recursively *)
let rec scan_directory dir =
  match Fs.read_dir dir with
  | Error _ -> []
  | Ok iter ->
      let entries = MutIterator.to_list iter in
      List.concat_map
        (fun entry ->
          let path = Path.(dir / entry) in
          match Fs.is_dir path with
          | Ok true ->
              (* Subdirectory *)
              let children = scan_directory path in
              [ (Path.basename entry, `Dir (path, children)) ]
          | Ok false -> (
              (* File *)
              match Path.extension path with
              | Some ext -> [ (Path.basename entry, `File (path, ext)) ]
              | None -> [])
          | Error _ -> [])
        entries

(** Sort entries so .mli files are processed before .ml files (REQ-051) *)
let sort_entries entries =
  List.sort
    (fun (_, e1) (_, e2) ->
      match (e1, e2) with
      | `File (_, ".mli"), `File (_, ".ml") -> -1
      | `File (_, ".ml"), `File (_, ".mli") -> 1
      | _ -> 0)
    entries

let rec do_scan ~t ~ctx entries src_dir =
  let sorted_entries = sort_entries entries in
  match sorted_entries with
  | [] -> ()
  | (name, entry) :: rest -> (
      match entry with
      | `File (path, ((".ml" | ".mli") as ext)) ->
          handle_ocaml_module ~t ~ctx path;
          do_scan ~t ~ctx rest src_dir
      | `File (path, ".c") ->
          handle_c_file ~t ~ctx path;
          do_scan ~t ~ctx rest src_dir
      | `File (path, ".h") ->
          handle_h_file ~t ~ctx path;
          do_scan ~t ~ctx rest src_dir
      | `File (_, _) ->
          (* Skip other files *)
          do_scan ~t ~ctx rest src_dir
      | `Dir (path, children) ->
          handle_library ~t ~ctx path name children src_dir;
          do_scan ~t ~ctx rest src_dir)

and handle_c_file ~t ~ctx path =
  let { parent_impl; _ } = ctx in
  let node = { file = Concrete path; open_modules = []; kind = C } in
  let c_node = G.add_node t.graph node in
  G.add_edge parent_impl ~depends_on:c_node

and handle_h_file ~t ~ctx path =
  let node = { file = Concrete path; open_modules = []; kind = H } in
  let _h_node = G.add_node t.graph node in
  ()

and handle_ocaml_module ~t ~ctx path =
  let { ns; aliases; parent_impl; parent_intf } = ctx in

  let mod_ = Module.make ~namespace:ns ~filename:path in
  let node = Ocaml_module.make_node mod_ aliases |> G.add_node t.graph in

  Module_registry.register t.registry mod_ node.id;

  (* If implementation, check for corresponding interface *)
  (match Module.kind mod_ with
  | `implementation -> (
      let mod_name = Module.module_name mod_ |> Module_name.to_string in
      try
        let node_ids = Module_registry.get_by_name t.registry mod_name in
        List.iter
          (fun intf_node_id ->
            let intf_node = G.get_node t.graph intf_node_id in
            match intf_node.value.kind with
            | MLI intf_mod
              when Module.module_name intf_mod
                   |> Module_name.to_string = mod_name ->
                G.add_edge node ~depends_on:intf_node
            | _ -> ())
          node_ids
      with Not_found -> ())
  | `interface -> ());

  let parent =
    match Module.kind mod_ with
    | `interface -> parent_intf
    | `implementation -> parent_impl
  in
  G.add_edge parent ~depends_on:node;
  List.iter
    (fun aliases_node -> G.add_edge node ~depends_on:aliases_node)
    aliases

and handle_library ~t ~ctx dir name children src_dir =
  let { ns; aliases; parent_impl; parent_intf } = ctx in

  let base_path =
    if Namespace.is_empty ns then Path.(src_dir / Path.v name)
    else Path.(dir / Path.v name)
  in

  let intf_file = Path.add_extension base_path ~ext:"mli" in
  let intf_mod = Module.make ~namespace:ns ~filename:intf_file in

  let impl_file = Path.add_extension base_path ~ext:"ml" in
  let impl_mod = Module.make ~namespace:ns ~filename:impl_file in

  let ns =
    Namespace.append ns (Module.module_name impl_mod |> Module_name.to_string)
  in

  (* Parse children to separate files from subdirectories *)
  let child_files =
    List.filter_map
      (fun (n, e) ->
        match e with
        | `File (p, (".ml" | ".mli")) ->
            Some (Module.make ~namespace:ns ~filename:p)
        | _ -> None)
      children
  in

  let child_dirs =
    List.filter_map
      (fun (n, e) ->
        match e with
        | `Dir (p, _) ->
            let module_name = Module_name.of_string n in
            let module_name_str = Module_name.to_string module_name in
            (* Check if there's a file with same name *)
            let has_file =
              List.exists
                (fun m ->
                  Module_name.to_string (Module.module_name m) = module_name_str)
                child_files
            in
            if has_file then None
            else
              Some
                (Module.make ~namespace:ns
                   ~filename:Path.(p / Path.v (n ^ ".ml")))
        | _ -> None)
      children
  in

  let child_modules = child_files @ child_dirs in

  (* Check if library interface files exist *)
  let library_interface_ml_path =
    List.find_map
      (fun (n, e) ->
        match e with
        | `File (p, ".ml") when n = name ^ ".ml" -> Some p
        | _ -> None)
      children
  in

  let library_interface_mli_path =
    List.find_map
      (fun (n, e) ->
        match e with
        | `File (p, ".mli") when n = name ^ ".mli" -> Some p
        | _ -> None)
      children
  in

  let has_library_interface_ml = library_interface_ml_path <> None in
  let has_library_interface_mli = library_interface_mli_path <> None in

  (* Filter out library interface files from children *)
  let children_without_lib =
    List.filter (fun (n, _) -> n <> name ^ ".ml" && n <> name ^ ".mli") children
  in

  (* Create aliases module *)
  let aliases_node =
    let node = Alias_module.make_node ns child_modules in
    G.add_node t.graph node
  in

  (* Create library interface *)
  let intf_node =
    let intf =
      Library_interface.make_node intf_mod child_modules
        (aliases @ [ aliases_node ])
        ~exists:has_library_interface_mli
        ~actual_path:library_interface_mli_path
    in
    G.add_node t.graph intf
  in
  Module_registry.register t.registry intf_mod intf_node.id;

  let impl_node =
    let impl =
      Library_interface.make_node impl_mod child_modules
        (aliases @ [ aliases_node ])
        ~exists:has_library_interface_ml ~actual_path:library_interface_ml_path
    in
    G.add_node t.graph impl
  in
  Module_registry.register t.registry impl_mod impl_node.id;

  (* Add edges *)
  G.add_edge intf_node ~depends_on:aliases_node;
  G.add_edge impl_node ~depends_on:aliases_node;
  G.add_edge impl_node ~depends_on:intf_node;

  let ctx =
    {
      ns;
      aliases = aliases @ [ aliases_node ];
      parent_impl = impl_node;
      parent_intf = intf_node;
    }
  in

  (* Sort children to process .mli before .ml *)
  let sorted_children =
    List.sort
      (fun (_, a) (_, b) ->
        let ext_a = match a with `File (_, ext) -> ext | _ -> "" in
        let ext_b = match b with `File (_, ext) -> ext | _ -> "" in
        match (ext_a, ext_b) with
        | ".mli", ".mli" -> 0
        | ".mli", _ -> -1
        | _, ".mli" -> 1
        | ".ml", ".ml" -> 0
        | ".ml", _ -> -1
        | _, ".ml" -> 1
        | _ -> 0)
      children_without_lib
  in

  do_scan ~t ~ctx sorted_children src_dir

(** Scan source files *)
let scan_sources t =
  let src_dir = Path.(t.package.path / Path.v "src") in
  let entries = scan_directory src_dir in

  let root_node = G.add_node t.graph root_node in

  let ctx =
    {
      ns = Namespace.empty;
      parent_impl = root_node;
      parent_intf = root_node;
      aliases = [];
    }
  in

  (* Treat the entire src directory as the root library *)
  handle_library ~t ~ctx src_dir t.package.name entries src_dir

(** Wire dependencies using ocamldep *)
let wire_dependencies t =
  G.iter
    (fun _node_id (node : dep G.node) ->
      let dep = node.value in
      match dep.kind with
      | ML mod_ | MLI mod_ ->
          let deps =
            match dep.file with
            | Generated _ -> []
            | Concrete path ->
                let cwd = Path.to_string t.package.path in
                let file = Path.to_string path in
                Ocamldep.deps ~toolchain:t.toolchain ~cwd ~file
                  ~package_namespace:t.namespace
          in

          List.iter
            (fun dep_mod_name ->
              let dep_name = Module_name.to_string dep_mod_name in
              try
                let node_ids =
                  Module_registry.get_by_name t.registry dep_name
                in
                List.iter
                  (fun dep_node_id ->
                    let dep_node = G.get_node t.graph dep_node_id in
                    match (node.value.kind, dep_node.value.kind) with
                    | MLI _, ML _ -> ()
                    | _ -> G.add_edge node ~depends_on:dep_node)
                  node_ids
              with Not_found -> ())
            deps
      | _ -> ())
    t.graph

(** Generate compilation actions from the module graph *)
let generate_actions t =
  let sorted_nodes =
    try G.topo_sort t.graph
    with G.Cycle cycle_ids ->
      failwith
        (Printf.sprintf "Cycle detected in module dependencies: %s"
           (String.concat " -> " (List.map G.Node_id.to_string cycle_ids)))
  in

  let actions = ref [] in
  let outputs = ref [] in
  let cmo_files = ref [] in

  (* Helper to get open modules *)
  let opens mods =
    List.filter_map
      (fun (node : dep G.node) ->
        match node.value.kind with
        | ML mod_ | MLI mod_ -> Some (Module.namespaced_name mod_)
        | _ -> None)
      mods
  in

  (* Generate actions for each node *)
  List.iter
    (fun (node : dep G.node) ->
      match node.value with
      | { kind = MLI mod_; file = Concrete path; open_modules; _ } ->
          let output = Module.cmi mod_ in
          let action =
            Actions.CompileInterface
              {
                source = Path.to_string path;
                output;
                includes = [ "." ];
                flags = List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := action :: !actions;
          outputs := output :: !outputs
      | { kind = ML mod_; file = Concrete path; open_modules; _ } ->
          let output = Module.cmo mod_ in
          let action =
            Actions.CompileImplementation
              {
                source = Path.to_string path;
                output;
                includes = [ "." ];
                flags = List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := action :: !actions;
          outputs := output :: !outputs;
          cmo_files := output :: !cmo_files
      | { kind = ML mod_; file = Generated { path; contents }; open_modules; _ }
        ->
          (* Write generated file *)
          let write_action =
            Actions.WriteFile
              { destination = Path.to_string path; content = contents }
          in
          actions := write_action :: !actions;

          (* Compile it *)
          let output = Module.cmo mod_ in
          let action =
            Actions.CompileImplementation
              {
                source = Path.to_string path;
                output;
                includes = [ "." ];
                flags = List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := action :: !actions;
          outputs := output :: !outputs;
          cmo_files := output :: !cmo_files
      | {
       kind = MLI mod_;
       file = Generated { path; contents };
       open_modules;
       _;
      } ->
          (* Write generated file *)
          let write_action =
            Actions.WriteFile
              { destination = Path.to_string path; content = contents }
          in
          actions := write_action :: !actions;

          (* Compile it *)
          let output = Module.cmi mod_ in
          let action =
            Actions.CompileInterface
              {
                source = Path.to_string path;
                output;
                includes = [ "." ];
                flags = List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := action :: !actions;
          outputs := output :: !outputs
      | { kind = C; file = Concrete path; _ } ->
          let src = Path.to_string path in
          let obj_file =
            Path.remove_extension path
            |> Path.add_extension ~ext:"o"
            |> Path.to_string
          in
          let action = Actions.CompileC { source = src; output = obj_file } in
          actions := action :: !actions;
          outputs := obj_file :: !outputs
      | { kind = H; file = Concrete path; _ } ->
          (* Header files just need to be available, no action needed *)
          ()
      | { kind = Root; _ } -> ()
      | _ -> ())
    sorted_nodes;

  (* Create library archive *)
  let library_name = String.capitalize_ascii t.package.name ^ ".cma" in
  if !cmo_files <> [] then (
    let archive_action =
      Actions.CreateLibrary
        {
          output = library_name;
          objects = List.rev !cmo_files;
          includes = [ "." ];
        }
    in
    actions := archive_action :: !actions;
    outputs := library_name :: !outputs);

  (* Add DeclareOutputs *)
  let declare_action = Actions.DeclareOutputs { outputs = List.rev !outputs } in

  (List.rev (declare_action :: !actions), List.rev !outputs)

(** Build the complete module graph for a package *)
let build ~node ~workspace =
  let t = create ~node ~workspace in

  (* Step 1: Scan source files and build file tree *)
  scan_sources t;

  (* Step 2: Wire dependencies with ocamldep *)
  wire_dependencies t;

  (* Step 3: Generate compilation actions *)
  let actions, outputs = generate_actions t in

  Ok (t, actions)
