(** Module Graph - Intra-package dependency graph for building a single package

    This is a port of minitusk's dep_graph.ml with full support for:
    - Namespacing
    - Directory-based libraries
    - Recursive sublibraries
    - Generated library interface modules
    - Alias files *)

open Std
open Std.Iter
open Model
open Ocaml

module G = Graph.SimpleGraph
(** Use Std.Graph for graph operations *)

(** Graph node representing a module or file to compile *)
type kind = ML of Module.t | MLI of Module.t | C | H | Other of string | Root

type file =
  | Concrete of Path.t
  | Generated of { path : Path.t; contents : string }

let file_to_string file =
  match file with
  | Concrete path -> Path.to_string path
  | Generated { path; _ } -> Path.to_string path ^ " (generated)"

type dep = { file : file; mutable open_modules : dep G.node list; kind : kind }

type t = {
  package : Package.t;
  toolchain : Toolchains.toolchain;
  namespace : Namespace.t;
  workspace : Workspace.t;
  graph : dep G.t;
  registry : Module_registry.t;
}
(** The module graph structure *)

type error = string

let root_node = { file = Concrete (Path.v ""); open_modules = []; kind = Root }

module Alias_module = struct
  let template (modules : Module.t list) =
    let header = "(* Alias module generated by tusk *)" in
    let unique_modules =
      modules
      |> List.filter_map (fun mod_ ->
          match Module.kind mod_ with
          | `interface -> None
          | `implementation ->
              let name = Module.module_name mod_ |> Module_name.to_string in
              let ns = Module.namespaced_name mod_ in
              Some (name, ns))
      |> List.sort_uniq (fun (n1, _) (n2, _) -> String.compare n1 n2)
    in
    let body =
      List.map
        (fun (name, ns) -> format "module %s = %s" name ns)
        unique_modules
    in
    String.concat "\n" (header :: body)

  let make_node (ns : Namespace.t) (modules : Module.t list) =
    let ns_prefix = Namespace.to_string ns in
    let filename =
      if ns_prefix = "" then "Aliases.ml-gen"
      else ns_prefix ^ "__Aliases.ml-gen"
    in
    (* Use relative path - alias files are at sandbox root *)
    let path = Path.v filename in
    (* Don't pass namespace - it's already in the filename *)
    let mod_ = Module.make ~namespace:Namespace.empty ~filename:path in
    let file = Generated { path; contents = template modules } in
    let kind = ML mod_ in
    { file; open_modules = []; kind }
end

module Library_interface = struct
  let template (children : Module.t list) =
    let header = "(* Library interface module generated by tusk *)" in
    let unique_modules =
      children
      |> List.map (fun mod_ ->
          let simple_name = Module.module_name mod_ |> Module_name.to_string in
          let qualified_name = Module.qualified_name mod_ in
          (simple_name, qualified_name))
      |> List.sort_uniq (fun (a, _) (b, _) -> String.compare a b)
    in
    let body =
      List.map
        (fun (simple, qualified) -> format "module %s = %s" simple qualified)
        unique_modules
    in
    String.concat "\n" (header :: body)

  let make_node (lib : Module.t) (children : Module.t list) aliases ~exists
      ~actual_path =
    let path =
      match actual_path with Some p -> p | None -> Module.filename lib
    in
    let file =
      if exists then Concrete path
      else Generated { path; contents = template children }
    in
    let kind =
      match Module.kind lib with
      | `interface -> MLI lib
      | `implementation -> ML lib
    in
    let open_modules = aliases in
    { file; open_modules; kind }
end

module Ocaml_module = struct
  let make_node (mod_ : Module.t) aliases =
    let path = Module.filename mod_ in
    let file = Concrete path in
    let kind =
      match Module.kind mod_ with
      | `interface -> MLI mod_
      | `implementation -> ML mod_
    in
    let open_modules = aliases in
    { file; open_modules; kind }
end

type scan_ctx = {
  ns : Namespace.t;
  parent_intf : dep G.node;
  parent_impl : dep G.node;
  aliases : dep G.node list;
}

(** Create a new module graph for a package *)
let create ~node:(build_node : Build_node.t) ~workspace =
  let package = build_node.package in
  let toolchain = build_node.toolchain in
  let namespace = Namespace.of_list [ String.capitalize_ascii package.name ] in

  Log.debug "[MODULE_GRAPH] Creating module graph for %s (namespace: %s)"
    package.name
    (Namespace.to_string namespace);

  {
    package;
    toolchain;
    namespace;
    workspace;
    graph = G.make ();
    registry = Module_registry.create ();
  }

(** Scan directory tree recursively *)
let rec scan_directory dir =
  match Fs.read_dir dir with
  | Error _ -> []
  | Ok iter ->
      let entries = MutIterator.to_list iter in
      List.concat_map
        (fun entry ->
          let path = Path.(dir / entry) in
          match Fs.is_dir path with
          | Ok true ->
              (* Subdirectory *)
              let children = scan_directory path in
              [ (Path.basename entry, `Dir (path, children)) ]
          | Ok false -> (
              (* File *)
              match Path.extension path with
              | Some ext -> [ (Path.basename entry, `File (path, ext)) ]
              | None -> [])
          | Error _ -> [])
        entries

(** Sort entries so .mli files are processed before .ml files (REQ-051) *)
let sort_entries entries =
  List.sort
    (fun (_, e1) (_, e2) ->
      match (e1, e2) with
      | `File (_, ".mli"), `File (_, ".ml") -> -1
      | `File (_, ".ml"), `File (_, ".mli") -> 1
      | _ -> 0)
    entries

let rec do_scan ~t ~ctx entries =
  let sorted_entries = sort_entries entries in
  match sorted_entries with
  | [] -> ()
  | (name, entry) :: rest -> (
      match entry with
      | `File (path, ((".ml" | ".mli") as ext)) ->
          handle_ocaml_module ~t ~ctx path;
          do_scan ~t ~ctx rest
      | `File (path, ".c") ->
          handle_c_file ~t ~ctx path;
          do_scan ~t ~ctx rest
      | `File (path, ".h") ->
          handle_h_file ~t ~ctx path;
          do_scan ~t ~ctx rest
      | `File (_, _) ->
          (* Skip other files *)
          do_scan ~t ~ctx rest
      | `Dir (path, children) ->
          handle_library ~t ~ctx path name children;
          do_scan ~t ~ctx rest)

and handle_c_file ~t ~ctx path =
  let { parent_impl; _ } = ctx in
  let node = { file = Concrete path; open_modules = []; kind = C } in
  let c_node = G.add_node t.graph node in
  G.add_edge parent_impl ~depends_on:c_node

and handle_h_file ~t ~ctx path =
  let { parent_impl; _ } = ctx in
  let node = { file = Concrete path; open_modules = []; kind = H } in
  let h_node = G.add_node t.graph node in
  (* H files must be available before C compilation, so make parent depend on them *)
  G.add_edge parent_impl ~depends_on:h_node

and handle_ocaml_module ~t ~ctx path =
  let { ns; aliases; parent_impl; parent_intf } = ctx in

  (* Skip binary modules - they will be compiled separately *)
  let path_str = Path.to_string path in
  let is_binary =
    List.exists
      (fun (bin : Package.binary) ->
        let bin_str = Path.to_string bin.path in
        let bin_basename = Filename.basename bin_str in
        let file_basename = Filename.basename path_str in
        bin_basename = file_basename)
      t.package.binaries
  in

  if is_binary then (
    Log.debug "[MODULE_GRAPH] Skipping binary module: %s" path_str;
    ())
  else
    let mod_ = Module.make ~namespace:ns ~filename:path in
    let node = Ocaml_module.make_node mod_ aliases |> G.add_node t.graph in

    Module_registry.register t.registry mod_ node.id;

    (* If implementation, check for corresponding interface *)
    (match Module.kind mod_ with
    | `implementation -> (
        let mod_name = Module.module_name mod_ |> Module_name.to_string in
        try
          let node_ids = Module_registry.get_by_name t.registry mod_name in
          List.iter
            (fun intf_node_id ->
              let intf_node = G.get_node t.graph intf_node_id in
              match intf_node.value.kind with
              | MLI intf_mod
                when Module.module_name intf_mod
                     |> Module_name.to_string = mod_name ->
                  G.add_edge node ~depends_on:intf_node
              | _ -> ())
            node_ids
        with Not_found -> ())
    | `interface -> ());

    let parent =
      match Module.kind mod_ with
      | `interface -> parent_intf
      | `implementation -> parent_impl
    in
    G.add_edge parent ~depends_on:node;
    List.iter
      (fun aliases_node -> G.add_edge node ~depends_on:aliases_node)
      aliases

and handle_library ~t ~ctx dir name children =
  let { ns; aliases; parent_impl; parent_intf } = ctx in

  (* Use relative paths for library interface files *)
  let base_path = Path.(dir / Path.v name) in
  let intf_file = Path.add_extension base_path ~ext:"mli" in
  let intf_mod = Module.make ~namespace:ns ~filename:intf_file in

  let impl_file = Path.add_extension base_path ~ext:"ml" in
  let impl_mod = Module.make ~namespace:ns ~filename:impl_file in

  let ns =
    Namespace.append ns (Module.module_name impl_mod |> Module_name.to_string)
  in

  (* Parse children to separate files from subdirectories *)
  (* IMPORTANT: Exclude the library interface files themselves (name.ml and name.mli) *)
  (* to avoid creating self-loops: lib.ml -> lib.ml *)
  (* Compare module names, not file names, to handle Pkg.ml vs pkg.ml *)
  let library_module_name =
    Module_name.of_string name |> Module_name.to_string
  in

  (* IMPORTANT: Exclude binary modules from the library interface *)
  (* Binary paths are stored as ABSOLUTE (e.g., /full/path/packages/tusk/src/main.ml) *)
  (* File paths during scanning are RELATIVE to package root (e.g., src/main.ml) *)
  (* So we need to make binary paths relative to compare them *)
  let is_binary_module p =
    let p_str = Path.to_string p in
    List.exists
      (fun (bin : Package.binary) ->
        let bin_abs = Path.to_string bin.path in
        let pkg_abs = Path.to_string t.package.path in
        (* Make binary path relative by removing package prefix *)
        let bin_rel =
          if String.starts_with ~prefix:(pkg_abs ^ "/") bin_abs then
            String.sub bin_abs
              (String.length pkg_abs + 1)
              (String.length bin_abs - String.length pkg_abs - 1)
          else bin_abs
        in
        let matches = p_str = bin_rel in
        Log.debug
          "[MODULE_GRAPH] Comparing: file=%s bin_abs=%s bin_rel=%s matches=%b"
          p_str bin_abs bin_rel matches;
        matches)
      t.package.binaries
  in

  let child_files =
    List.filter_map
      (fun (n, e) ->
        match e with
        | `File (p, (".ml" | ".mli")) ->
            (* Compare module names, not file names *)
            (* n is already a string basename, just remove extension *)
            let file_module_name =
              Filename.remove_extension n
              |> Module_name.of_string |> Module_name.to_string
            in
            if file_module_name = library_module_name then
              (* This is the library interface file itself - skip it *)
              None
            else
              let is_bin = is_binary_module p in
              if is_bin then
                Log.debug "[MODULE_GRAPH] Filtered out binary from library: %s"
                  (Path.to_string p);
              if not is_bin then Some (Module.make ~namespace:ns ~filename:p)
              else None
        | _ -> None)
      children
  in

  let child_dirs =
    List.filter_map
      (fun (n, e) ->
        match e with
        | `Dir (p, _) ->
            let module_name = Module_name.of_string n in
            let module_name_str = Module_name.to_string module_name in
            (* Check if there's a file with same name *)
            let has_file =
              List.exists
                (fun m ->
                  Module_name.to_string (Module.module_name m) = module_name_str)
                child_files
            in
            if has_file then None
            else
              Some
                (Module.make ~namespace:ns
                   ~filename:Path.(p / Path.v (n ^ ".ml")))
        | _ -> None)
      children
  in

  let child_modules = child_files @ child_dirs in

  (* Check if library interface files exist *)
  let library_interface_ml_path =
    List.find_map
      (fun (n, e) ->
        match e with
        | `File (p, ".ml") ->
            (* n is already a string basename, just remove extension *)
            let file_module_name =
              Filename.remove_extension n
              |> Module_name.of_string |> Module_name.to_string
            in
            if file_module_name = library_module_name then Some p else None
        | _ -> None)
      children
  in

  let library_interface_mli_path =
    List.find_map
      (fun (n, e) ->
        match e with
        | `File (p, ".mli") ->
            (* n is already a string basename, just remove extension *)
            let file_module_name =
              Filename.remove_extension n
              |> Module_name.of_string |> Module_name.to_string
            in
            if file_module_name = library_module_name then Some p else None
        | _ -> None)
      children
  in

  let has_library_interface_ml = library_interface_ml_path <> None in
  let has_library_interface_mli = library_interface_mli_path <> None in

  if has_library_interface_ml || has_library_interface_mli then
    Log.debug
      "[MODULE_GRAPH] Library %s has concrete interface files: ml=%b mli=%b"
      name has_library_interface_ml has_library_interface_mli;

  let children_without_lib =
    List.filter
      (fun (n, _) ->
        (* Compare module names, not file names *)
        (* n is already a string basename, just remove extension *)
        let file_module_name =
          Filename.remove_extension n
          |> Module_name.of_string |> Module_name.to_string
        in
        let keep = file_module_name <> library_module_name in
        if not keep then
          Log.debug
            "[MODULE_GRAPH] Filtering out library interface file: %s from \
             library %s"
            n name;
        keep)
      children
  in

  (* Create aliases module *)
  let aliases_node =
    let node = Alias_module.make_node ns child_modules in
    G.add_node t.graph node
  in

  (* Create library interface *)
  (* Top-level: open just this level's aliases (Kernel__Aliases) *)
  (* Subdirectory: open parent + this level's aliases (Kernel__Aliases + Kernel__Crypto__Aliases) *)
  let lib_aliases =
    if Namespace.is_empty ns then [ aliases_node ]
    else aliases @ [ aliases_node ]
  in

  let intf_node =
    let intf =
      Library_interface.make_node intf_mod child_modules lib_aliases
        ~exists:has_library_interface_mli
        ~actual_path:library_interface_mli_path
    in
    G.add_node t.graph intf
  in
  Module_registry.register t.registry intf_mod intf_node.id;

  let impl_node =
    let impl =
      Library_interface.make_node impl_mod child_modules lib_aliases
        ~exists:has_library_interface_ml ~actual_path:library_interface_ml_path
    in
    G.add_node t.graph impl
  in
  Module_registry.register t.registry impl_mod impl_node.id;

  (* Add edges *)
  G.add_edge intf_node ~depends_on:aliases_node;
  G.add_edge impl_node ~depends_on:aliases_node;
  G.add_edge impl_node ~depends_on:intf_node;

  let ctx =
    {
      ns;
      aliases = aliases @ [ aliases_node ];
      parent_impl = impl_node;
      parent_intf = intf_node;
    }
  in

  (* Sort children to process .mli before .ml *)
  let sorted_children =
    List.sort
      (fun (_, a) (_, b) ->
        let ext_a = match a with `File (_, ext) -> ext | _ -> "" in
        let ext_b = match b with `File (_, ext) -> ext | _ -> "" in
        match (ext_a, ext_b) with
        | ".mli", ".mli" -> 0
        | ".mli", _ -> -1
        | _, ".mli" -> 1
        | ".ml", ".ml" -> 0
        | ".ml", _ -> -1
        | _, ".ml" -> 1
        | _ -> 0)
      children_without_lib
  in

  do_scan ~t ~ctx sorted_children;

  (* Library interface files must be compiled AFTER their children *)
  (* For CONCRETE library interfaces: depend only on child_files to avoid cycles *)
  (* For GENERATED library interfaces: depend on child_modules (includes subdirectories) *)
  (* because the generated content references sublibrary interfaces *)
  let deps_for_library_interface =
    if has_library_interface_ml && has_library_interface_mli then
      (* Concrete library interface - only depend on files in this directory *)
      child_files
    else
      (* Generated library interface - depend on all children including subdirectories *)
      child_modules
  in

  Log.debug "[MODULE_GRAPH] Library %s has %d child modules for interface deps:"
    name
    (List.length deps_for_library_interface);
  List.iter
    (fun m ->
      Log.debug "[MODULE_GRAPH]   - %s (%s)"
        (Module.module_name m |> Module_name.to_string)
        (Module.filename m |> Path.to_string))
    deps_for_library_interface;

  List.iter
    (fun child_mod ->
      try
        let child_node_ids =
          Module_registry.get_by_name t.registry
            (Module.module_name child_mod |> Module_name.to_string)
        in
        List.iter
          (fun child_node_id ->
            let child_node = G.get_node t.graph child_node_id in
            Log.debug "[MODULE_GRAPH]   Adding edge: %s.ml/mli -> %s" name
              (file_to_string child_node.value.file);
            (* Add dependency from library interface to child *)
            G.add_edge intf_node ~depends_on:child_node;
            G.add_edge impl_node ~depends_on:child_node)
          child_node_ids
      with Not_found -> ())
    deps_for_library_interface

(** Scan source files *)
let scan_sources t sandbox_dir (sources : Sandbox.entry list) =
  (* Use pre-copied sources from sandbox - paths are already relative *)
  let root_node = G.add_node t.graph root_node in

  let ctx =
    {
      ns = Namespace.empty;
      parent_impl = root_node;
      parent_intf = root_node;
      aliases = [];
    }
  in

  (* Treat the entire src directory as the root library *)
  handle_library ~t ~ctx (Path.v "src") t.package.name sources

(** Wire dependencies using ocamldep *)
let wire_dependencies t sandbox_dir =
  Log.debug "[MODULE_GRAPH] Wiring dependencies with ocamldep";

  (* Collect all concrete files and their node info *)
  let all_nodes = G.map t.graph ~fn:(fun (node_id, node) -> (node_id, node)) in

  let files_with_nodes =
    List.filter_map
      (fun (node_id, (node : dep G.node)) ->
        let dep = node.value in
        match dep.kind with
        | ML _ | MLI _ -> (
            match dep.file with
            | Concrete path -> Some (path, node_id, node)
            | Generated _ -> None)
        | _ -> None)
      all_nodes
  in

  let files = List.map (fun (path, _, _) -> path) files_with_nodes in

  Log.debug "[MODULE_GRAPH] Running batch ocamldep for %d files"
    (List.length files);

  (* Run ocamldep once for all files *)
  let file_deps_map =
    Ocamldep.batch_deps ~toolchain:t.toolchain ~cwd:sandbox_dir ~files
      ~package_namespace:t.namespace
  in

  (* Create a lookup table for quick access *)
  let deps_table = Hashtbl.create (List.length file_deps_map) in
  List.iter
    (fun (file, deps) -> Hashtbl.add deps_table (Path.to_string file) deps)
    file_deps_map;

  (* Map back to (node_id, node, deps) format *)
  let deps =
    List.filter_map
      (fun (path, node_id, node) ->
        let path_str = Path.to_string path in
        match Hashtbl.find_opt deps_table path_str with
        | Some deps ->
            Log.debug "[MODULE_GRAPH] File %s has %d deps" path_str
              (List.length deps);
            Some (node_id, node, deps)
        | None ->
            Log.debug "[MODULE_GRAPH] No deps found for %s" path_str;
            Some (node_id, node, []))
      files_with_nodes
  in

  Log.debug "[MODULE_GRAPH] Processed %d files with dependencies"
    (List.length deps);

  let handle_edges node_id (node : dep G.node) deps =
    let dep = node.value in

    Log.debug "[MODULE_GRAPH] handle_edges called for %s with %d deps"
      (file_to_string dep.file) (List.length deps);

    if deps <> [] then
      Log.debug "[MODULE_GRAPH]   %s depends on: %s" (file_to_string dep.file)
        (String.concat ", " (List.map Module_name.to_string deps));

    let edges_collected = ref 0 in
    let edges_wired = ref 0 in
    let edges_skipped = ref 0 in

    List.iter
      (fun dep_mod_name ->
        let dep_name = Module_name.to_string dep_mod_name in
        try
          let dep_node_ids = Module_registry.get_by_name t.registry dep_name in
          List.iter
            (fun dep_node_id ->
              incr edges_collected;
              let dep_node = G.get_node t.graph dep_node_id in

              match (dep.kind, dep_node.value.kind) with
              | MLI _, ML _ ->
                  incr edges_skipped;
                  Log.debug
                    "[MODULE_GRAPH]     SKIPPED edge (MLI->ML): %s -> %s"
                    (file_to_string dep.file)
                    (file_to_string dep_node.value.file)
              | _ ->
                  incr edges_wired;
                  Log.debug "[MODULE_GRAPH]     Adding edge: %s -> %s"
                    (file_to_string dep.file)
                    (file_to_string dep_node.value.file);
                  G.add_edge node ~depends_on:dep_node)
            dep_node_ids
        with Not_found ->
          Log.debug
            "[MODULE_GRAPH]     WARNING: Module %s not found in registry"
            dep_name)
      deps;

    if !edges_collected > 0 then
      Log.debug
        "[MODULE_GRAPH]   Summary for %s: collected=%d, wired=%d, skipped=%d"
        (file_to_string dep.file) !edges_collected !edges_wired !edges_skipped
  in

  Log.debug "[MODULE_GRAPH] Processing %d modules with dependencies"
    (List.length deps);
  List.iter (fun (id, node, dep) -> handle_edges id node dep) deps;
  Log.debug "[MODULE_GRAPH] Finished wiring dependencies";

  (* Verify graph structure after wiring *)
  let total_edges = ref 0 in
  G.iter t.graph ~fn:(fun node_id node ->
      let dep_count = List.length node.deps in
      total_edges := !total_edges + dep_count;
      if dep_count > 0 then
        Log.debug "[MODULE_GRAPH] Graph state: %s has %d edges"
          (file_to_string node.value.file)
          dep_count);
  Log.debug "[MODULE_GRAPH] Total edges in graph: %d" !total_edges

(** Generate compilation actions from the module graph *)
let generate_actions (t : t) (node : Build_node.t) (build_graph : Build_graph.t)
    =
  Log.debug "[MODULE_GRAPH] Generating compilation actions";
  Log.debug "[MODULE_GRAPH] About to call topo_sort on graph";
  let sorted_nodes =
    try
      Log.debug "[MODULE_GRAPH] Calling G.topo_sort...";
      let result = G.topo_sort t.graph in
      Log.debug "[MODULE_GRAPH] G.topo_sort returned successfully";
      Log.debug "[MODULE_GRAPH] Topo sort order (first 20):";
      List.iteri
        (fun i (node : dep G.node) ->
          if i < 20 then
            Log.debug "[MODULE_GRAPH]   %d. %s (deps: %d)" i
              (file_to_string node.value.file)
              (List.length node.deps))
        result;
      Log.debug "[MODULE_GRAPH] Topo sort order (last 10):";
      let len = List.length result in
      List.iteri
        (fun i (node : dep G.node) ->
          if i >= len - 10 then
            Log.debug "[MODULE_GRAPH]   %d. %s (deps: %d)" i
              (file_to_string node.value.file)
              (List.length node.deps))
        result;
      result
    with
    | G.Cycle cycle_ids ->
        let cycle_str =
          String.concat " -> " (List.map G.Node_id.to_string cycle_ids)
        in
        Log.debug "[MODULE_GRAPH] ERROR: Cycle detected in module dependencies!";
        Log.debug "[MODULE_GRAPH] Cycle: %s" cycle_str;
        (* Try to get more details about the nodes in the cycle *)
        List.iter
          (fun node_id ->
            try
              let node = G.get_node t.graph node_id in
              Log.debug "[MODULE_GRAPH]   - %s (%s)"
                (G.Node_id.to_string node_id)
                (file_to_string node.value.file)
            with _ ->
              Log.debug "[MODULE_GRAPH]   - %s (unknown)"
                (G.Node_id.to_string node_id))
          cycle_ids;
        failwith (format "Cycle detected in module dependencies: %s" cycle_str)
    | exn ->
        Log.debug "[MODULE_GRAPH] ERROR: Exception in topo_sort: %s"
          (Exception.to_string exn);
        raise exn
  in

  Log.debug "[MODULE_GRAPH] Topologically sorted %d nodes"
    (List.length sorted_nodes);

  let actions = ref [] in
  let outputs = ref [] in
  let cmx_files = ref [] in
  let c_objects = ref [] in
  (* Track .o files from C compilation *)

  (* Files are already in sandbox - no need to copy *)
  Log.debug "[MODULE_GRAPH] Generating compilation actions...";

  (* Helper to check if a file path is a binary source *)
  let is_binary_source path =
    List.exists
      (fun (bin : Package.binary) -> Path.equal bin.path path)
      t.package.binaries
  in

  (* Filter out binary sources from library compilation *)
  let library_nodes =
    List.filter
      (fun (node : dep G.node) ->
        match node.value.file with
        | Concrete path -> not (is_binary_source path)
        | Generated _ -> true)
      sorted_nodes
  in

  Log.debug
    "[MODULE_GRAPH] Filtered %d binary sources, %d library modules remain"
    (List.length sorted_nodes - List.length library_nodes)
    (List.length library_nodes);

  (* Helper to get open modules *)
  let opens mods =
    List.filter_map
      (fun (node : dep G.node) ->
        match node.value.kind with
        | ML mod_ | MLI mod_ -> Some (Module.namespaced_name mod_)
        | _ -> None)
      mods
  in

  (* Generate actions for library modules (excluding binaries) *)
  List.iter
    (fun (node : dep G.node) ->
      Log.debug "[MODULE_GRAPH]   Processing library node: %s"
        (file_to_string node.value.file);
      match node.value with
      | { kind = MLI mod_; file = Concrete path; open_modules; _ } ->
          Log.debug "[MODULE_GRAPH]     -> MLI (Concrete)";
          (* Use absolute sandbox path *)
          let cmi_output = Module.cmi mod_ in
          let cmti_output = Module.cmti mod_ in
          let compile_action =
            Actions.CompileInterface
              {
                source = path;
                output = cmi_output;
                includes = [ Path.v "." ];
                flags = List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := compile_action :: !actions;
          outputs := cmti_output :: cmi_output :: !outputs
      | { kind = ML mod_; file = Concrete path; open_modules; _ } ->
          Log.debug "[MODULE_GRAPH]     -> ML (Concrete)";
          (* Use absolute sandbox path *)
          let cmx_output = Module.cmx mod_ in
          let cmi_output = Module.cmi mod_ in
          let cmt_output = Module.cmt mod_ in
          let compile_action =
            Actions.CompileImplementation
              {
                source = path;
                output = cmx_output;
                includes = [ Path.v "." ];
                flags = List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := compile_action :: !actions;
          cmx_files := cmx_output :: !cmx_files;
          outputs := cmt_output :: cmi_output :: !outputs
      | { kind = ML mod_; file = Generated { path; contents }; open_modules; _ }
        ->
          Log.debug "[MODULE_GRAPH]     -> ML (Generated): %s"
            (Path.to_string path);
          (* Write generated file *)
          let write_action =
            Actions.WriteFile { destination = path; content = contents }
          in
          actions := write_action :: !actions;

          (* Compile it *)
          let cmx_output = Module.cmx mod_ in
          let cmi_output = Module.cmi mod_ in
          let cmt_output = Module.cmt mod_ in
          (* Check if this is an alias file - they need -no-alias-deps and produce .cmi *)
          let is_alias_file =
            let filename = Path.to_string path in
            String.ends_with ~suffix:"Aliases.ml-gen" filename
          in
          let base_flags =
            if is_alias_file then
              [
                Ocamlc.NoAliasDeps;
                Ocamlc.Warning [ Ocamlc.NoCmiFile ];
                Ocamlc.Impl path;
              ]
            else [ Ocamlc.Impl path ]
          in
          let action =
            Actions.CompileImplementation
              {
                source = path;
                output = cmx_output;
                includes = [ Path.v "." ];
                flags =
                  base_flags
                  @ List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := action :: !actions;
          cmx_files := cmx_output :: !cmx_files;
          (* Generated .ml files always produce .cmi and .cmt (no separate .mli) *)
          outputs := cmt_output :: cmi_output :: !outputs
      | {
       kind = MLI mod_;
       file = Generated { path; contents };
       open_modules;
       _;
      } ->
          Log.debug "[MODULE_GRAPH]     -> MLI (Generated): %s"
            (Path.to_string path);
          (* Write generated file *)
          let write_action =
            Actions.WriteFile { destination = path; content = contents }
          in
          actions := write_action :: !actions;

          (* Compile it *)
          let cmi_output = Module.cmi mod_ in
          let cmti_output = Module.cmti mod_ in
          let action =
            Actions.CompileInterface
              {
                source = path;
                output = cmi_output;
                includes = [ Path.v "." ];
                flags = List.map (fun m -> Ocamlc.Open m) (opens open_modules);
              }
          in
          actions := action :: !actions;
          outputs := cmti_output :: cmi_output :: !outputs
      | { kind = C; file = Concrete path; _ } ->
          Log.debug "[MODULE_GRAPH]     -> C file";
          (* Use absolute sandbox path *)
          let obj_file =
            Path.remove_extension path |> Path.add_extension ~ext:"o"
          in
          (* Use basename for output tracking *)
          let output_name = Path.basename obj_file |> Path.v in
          let compile_action =
            Actions.CompileC { source = path; output = output_name }
          in
          actions := compile_action :: !actions;
          outputs := output_name :: !outputs;
          c_objects := output_name :: !c_objects
      | { kind = H; file = Concrete path; _ } ->
          Log.debug "[MODULE_GRAPH]     -> H file";
          (* Header files are already in sandbox via CopyDir, no action needed *)
          ()
      | { kind = Root; _ } ->
          Log.debug "[MODULE_GRAPH]     -> Root";
          ()
      | _ ->
          Log.debug "[MODULE_GRAPH]     -> Other";
          ())
    library_nodes;

  Log.debug "[MODULE_GRAPH] Finished processing all %d library nodes"
    (List.length library_nodes);

  (* Create library archive *)
  let library_name = Module_name.(of_string t.package.name |> cmxa) in
  let static_lib_name = Module_name.(of_string t.package.name |> a) in
  if !cmx_files <> [] then (
    (* Include both .cmx files and .o files (C stubs) in the library *)
    (* sorted_nodes is in topo order (dependencies first), but we build cmx_files *)
    (* by prepending, which reverses the order. So we need to reverse it back! *)
    Log.debug "[MODULE_GRAPH] cmx_files BEFORE reverse (first 10):";
    List.iteri
      (fun i obj ->
        if i < 10 then
          Log.debug "[MODULE_GRAPH]   %d. %s" i (Path.to_string obj))
      !cmx_files;
    let all_objects = List.rev !cmx_files @ List.rev !c_objects in
    Log.debug
      "[MODULE_GRAPH] Creating library with %d objects (%d cmx + %d c objects)"
      (List.length all_objects) (List.length !cmx_files)
      (List.length !c_objects);
    Log.debug "[MODULE_GRAPH] Link order AFTER reverse (first 20):";
    List.iteri
      (fun i obj ->
        if i < 20 then
          Log.debug "[MODULE_GRAPH]   %d. %s" i (Path.to_string obj))
      all_objects;
    let archive_action =
      Actions.CreateLibrary
        {
          output = library_name;
          objects = all_objects;
          includes = [ Path.v "." ];
        }
    in
    actions := archive_action :: !actions;
    (* Native compilation produces both .cmxa and .a files *)
    outputs := library_name :: static_lib_name :: !outputs);

  (* Create executables for binaries declared in [[bin]] *)
  Log.debug "[MODULE_GRAPH] Package has %d binaries to build"
    (List.length t.package.binaries);
  List.iter
    (fun (binary : Package.binary) ->
      Log.debug "[MODULE_GRAPH] Creating executable: %s from %s" binary.name
        (Path.to_string binary.path);

      (* Compile the binary's source file *)
      let binary_mod =
        Module.make ~namespace:Namespace.empty ~filename:binary.path
      in
      let binary_cmx = Module.cmx binary_mod in

      Log.debug "[MODULE_GRAPH] Compiling binary module from: %s"
        (Path.to_string binary.path);

      (* Compile the binary implementation *)
      (* The binary accesses library modules via the package interface (e.g., Tusk.Cli) *)
      let compile_binary_action =
        Actions.CompileImplementation
          {
            source = binary.path;
            output = binary_cmx;
            includes = [ Path.v "." ];
            flags = [];
          }
      in
      actions := compile_binary_action :: !actions;

      (* Get topologically sorted dependencies *)
      let sorted_deps =
        Build_graph.filter_for_package build_graph t.package.name
        |> Build_graph.topological_sort
      in

      (* Get dependency .cmxa files in topological order *)
      let dep_libraries =
        List.filter_map
          (fun dep_node ->
            let dep_pkg_name = dep_node.Build_node.package.name in
            (* Skip unix (handled separately) and skip ourselves *)
            if dep_pkg_name = "unix" || dep_pkg_name = t.package.name then None
            else
              let dep_name = Module_name.of_string dep_pkg_name in
              Some (Module_name.cmxa dep_name))
          sorted_deps
      in

      (* Check if we or any of our dependencies need unix *)
      let has_unix_dep =
        List.exists
          (fun dep_node ->
            List.exists
              (fun (dep : Package.dependency) -> dep.name = "unix")
              dep_node.Build_node.package.dependencies)
          sorted_deps
      in
      let includes =
        if has_unix_dep then Path.[ v "."; v "+unix" ] else Path.[ v "." ]
      in

      (* Libraries: unix first (if needed), then topologically sorted deps, then our library *)
      let libraries =
        (if has_unix_dep then Path.[ v "unix.cmxa" ] else [])
        @ dep_libraries @ [ library_name ]
      in

      let binary_output = Path.v binary.name in
      let exe_action =
        Actions.CreateExecutable
          {
            output = binary_output;
            objects = [ binary_cmx ];
            libraries;
            includes;
          }
      in
      actions := exe_action :: !actions;
      outputs := binary_output :: !outputs)
    t.package.binaries;

  let outputs = List.rev !outputs in

  (* Add DeclareOutputs *)
  let declare_action = Actions.DeclareOutputs { outputs } in

  (List.rev (declare_action :: !actions), outputs)

(** Build the complete module graph for a package *)
let build ~node ~workspace ~build_graph ~sandbox =
  Log.debug "[MODULE_GRAPH] ===== Building module graph for %s ====="
    node.Build_node.package.name;
  let t = create ~node ~workspace in

  (* Step 1: Scan source files and build file tree *)
  Log.debug "[MODULE_GRAPH] Step 1: Using sandbox source files";
  let sandbox_dir = Sandbox.get_sandbox_dir sandbox in
  let sources = Sandbox.sources sandbox in
  scan_sources t sandbox_dir sources;

  (* Step 2: Wire dependencies with ocamldep *)
  Log.debug "[MODULE_GRAPH] Step 2: Wiring dependencies";
  wire_dependencies t sandbox_dir;

  (* Step 3: Generate compilation actions *)
  Log.debug "[MODULE_GRAPH] Step 3: Generating actions";
  let actions, outputs = generate_actions t node build_graph in

  Log.debug "[MODULE_GRAPH] ===== Completed module graph for %s ====="
    node.Build_node.package.name;

  Ok (t, actions, outputs)
