[package]
name = "raml-cli"
version = "0.0.33"
public = false

[lib]
path = "src/raml_cli.ml"

[[bin]]
name = "raml"
path = "src/main.ml"

[dependencies]
std = "*"
raml = { path = "../raml", version = "*" }
