[package]
name = "email"
version = "0.1.0"

[lib]
path = "src/email.ml"

[dependencies]
std = { path = "../std" }
miniriot = { path = "../miniriot" }
mime = { path = "../mime" }

[[bin]]
name = "mbox"
path = "examples/mbox_reader.ml"

[[bin]]
name = "parser_tests"
path = "tests/parser_tests.ml"
