[package]
name = "riot-check"
version = "0.0.31"
description = "Typechecking command implementation for Riot"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_check.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
riot-planner = { path = "../riot-planner", version = "*" }
riot-build = { path = "../riot-build", version = "*" }
riot-store = { path = "../riot-store", version = "*" }
riot-toolchain = { path = "../riot-toolchain", version = "*" }
riot-deps = { path = "../riot-deps", version = "*" }
tty = { path = "../tty", version = "*" }
typ = { path = "../typ", version = "*" }
contentstore = { path = "../contentstore", version = "*" }
