[package]
name = "minttea"
version = "0.0.41"
description = "Elm-style terminal UI framework"
license = "Apache-2.0"
public = true

[lib]
path = "src/minttea.ml"

[dependencies]
colors = { path ="../colors", version = "*" }
gooey = { path = "../gooey", version = "*" }
std = { path = "../std", version = "*" }
tty = { path = "../tty", version = "*" }

[build-dependencies]
std = { path = "../std", version = "*" }

[[command]]
name = "demo"
help = "Run a minttea TUI demo"
path = "src/demo_cmd.ml"
