[package]
name = "minttea"
version = "0.1.0"

[lib]
path = "src/minttea.ml"

[dependencies]
colors = { path ="../colors" }
gooey = { path = "../gooey" }
std = { path = "../std" }
tty = { path = "../tty" }

[[command]]
name = "demo"
help = "Run a minttea TUI demo"
path = "src/demo_cmd.ml"
