[package]
name = "minttea"
version = "0.1.0"
description = "Elm-style terminal UI framework for OCaml."
license = "Apache-2.0"
public = true

[lib]
path = "src/minttea.ml"

[dependencies]
colors = { path ="../colors" }
gooey = { path = "../gooey" }
std = { path = "../std" }
tty = { path = "../tty" }

[build-dependencies]
std = { path = "../std" }

[[command]]
name = "demo"
help = "Run a minttea TUI demo"
path = "src/demo_cmd.ml"
