[package]
name = "tusk-init"
version = "0.0.1"
description = "Workspace and package scaffolding for Tusk."
license = "Apache-2.0"
public = true

[lib]
path = "src/tusk_init.ml"

[dependencies]
std = { path = "../std", version = "*" }
tusk-model = { path = "../tusk-model", version = "*" }
