[package]
name = "tusk-executor"
version = "0.1.0"

[package.lib]
path = "src/TuskExecutor.ml"

[dependencies]
std = "*"
miniriot = "*"
tusk-model = "*"
tusk-planner = "*"
tusk-toolchain = "*"
tusk-store = "*"

[[bin]]
name = "executor_tests"
path = "tests/executor_tests.ml"

[[bin]]
name = "caching_tests"
path = "tests/caching_tests.ml"
