[package]
name = "tusk-executor"
version = "0.0.1"
description = "Build execution and result aggregation for Tusk."
license = "Apache-2.0"
public = true

[lib]
path = "src/tusk_executor.ml"

[dependencies]
std = "*"
tusk-model = "*"
tusk-planner = "*"
tusk-toolchain = "*"
tusk-store = "*"
