[package]
name = "parquet"
version = "0.0.1"
description = "Standalone Parquet file reader/writer and metadata codec"
license = "Apache-2.0"
public = true

[lib]
path = "src/parquet.ml"

[dependencies]
std = { path = "../std", version = "*" }
