[package]
name = "tusk-pm"
version = "0.1.0"
description = "Package management and dependency solving for Tusk."
license = "Apache-2.0"
public = true

[lib]
path = "src/tusk_pm.ml"

[[bin]]
name = "pm_tests"
path = "tests/pm_tests.ml"

[dependencies]
std = { path = "../std" }
tusk-model = { path = "../tusk-model" }
pkgs-ml = { path = "../pkgs-ml" }
tusk-fmt = { path = "../tusk-fmt" }
tusk-fix = { path = "../tusk-fix" }
tusk-planner = { path = "../tusk-planner" }
tusk-executor = { path = "../tusk-executor" }
tusk-store = { path = "../tusk-store" }
tusk-toolchain = { path = "../tusk-toolchain" }
