[package]
name = "human-units"
version = "0.0.42"
description = "Human-readable byte and duration formatting"
license = "Apache-2.0"
public = true

[lib]
path = "src/human_units.ml"

[dependencies]
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
