[package]
name = "serde-toml"
version = "0.0.43"
description = "TOML support for the Serde serialization framework"
public = true
license = "Apache-2.0"

[lib]
path = "src/serde_toml.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
