[package]
name = "mime"
version = "0.0.43"
description = "MIME parsing and rendering helpers"
license = "Apache-2.0"
public = true

[lib]
path = "src/mime.ml"

[dependencies]
std = { path = "../std", version = "*" }
