[package]
name = "mime"
version = "0.1.0"

[lib]
path = "src/mime.ml"

[dependencies]
std = { path = "../std" }
miniriot = { path = "../miniriot" }

[[bin]]
name = "rfc2231_tests"
path = "tests/rfc2231_tests.ml"


