[package]
name = "krasny"
version = "0.0.34"
description = "Document layout and OCaml formatter"
license = "Apache-2.0"
public = true

[lib]
path = "src/krasny.ml"

[[bin]]
name = "krasny"
path = "src/main.ml"

[dependencies]
std = { path = "../std", version = "*" }
syn = { path = "../syn", version = "*" }
