[package]
name = "krasny"
version = "0.1.0"
description = "Document layout and OCaml code formatting engine."
license = "Apache-2.0"
public = true

[lib]
path = "src/krasny.ml"

[[bin]]
name = "krasny"
path = "src/main.ml"

[[bin]]
name = "format_tests"
path = "tests/format_tests.ml"

[dependencies]
std = { path = "../std" }
syn = { path = "../syn" }
