module Snake_case_type_names = Snake_case_type_names
module Descriptive_type_variables = Descriptive_type_variables
module Snake_case_function_names = Snake_case_function_names
module Class_case_module_names = Class_case_module_names
module Snake_case_variable_names = Snake_case_variable_names
module No_prime_variables = No_prime_variables
