[package]
name = "kernel"
description = "Platform abstraction layer for Riot"
version = "0.0.36"
license = "Apache-2.0"
public = true

[riot.fix]
rules = [ "-no-stdlib", "-no-positional-bool-parameters" ]

[lib]
path = "src/kernel.ml"

[target.macos]
cc_flags = [ "-I/opt/homebrew/opt/pcre2/include" ]
ld_flags = [
  "-L/opt/homebrew/opt/pcre2/lib",
  "-lpcre2-8",
  "-framework",
  "CoreFoundation",
  "-framework",
  "CoreServices",
]

[target.linux]
cc_flags = []
ld_flags = [ "-lpcre2-8" ]

[dependencies]

[dev-dependencies]
std = { path = "../std", version = "*" }
propane = { path = "../propane", version = "*" }

[build-dependencies]
fixme = { path = "../fixme", version = "*" }
