[package]
name = "kernel"
version = "0.0.1"

[lib]
path = "src/kernel.ml"

[target.macos]
cc_flags = ["-framework", "CoreFoundation", "-framework", "CoreServices", "-I/opt/homebrew/opt/openssl@3/include"]
ld_flags = ["-L/opt/homebrew/opt/openssl@3/lib", "-lssl", "-lcrypto"]

[target.linux]
cc_flags = []
ld_flags = ["-lssl", "-lcrypto"]

[dependencies]
stdlib = "*"
dynlink = "*"
unix = "*"
