[package]
name = "kernel"
version = "0.0.1"
public = true

[tusk.fix]
rules = [ "-no-stdlib" ]

[lib]
path = "src/kernel.ml"

[target.macos]
cc_flags = ["-I/opt/homebrew/opt/openssl@3/include"]
ld_flags = [
  "-framework", "CoreFoundation", 
  "-framework", "CoreServices", 
  "-framework", "Security",
  "-L/opt/homebrew/opt/openssl@3/lib", 
  "-lssl", 
  "-lcrypto"
]

[target.linux]
cc_flags = []
ld_flags = ["-lssl", "-lcrypto", "-luuid"]

[dependencies]
stdlib = "*"
dynlink = "*"
unix = "*"
