[package]
name = "riot-planner"
version = "0.0.36"
description = "Dependency graph construction and build planning"
license = "Apache-2.0"
public = false

[lib]
path = "src/Riot_planner.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
riot-store = { path = "../riot-store", version = "*" }
riot-toolchain = { path = "../riot-toolchain", version = "*" }
syn = { path = "../syn", version = "*" }
serde = { path = "../serde", version = "*" }
serde-json = { path = "../serde-json", version = "*" }
