name = "riot-registry"
main = "worker.ts"
compatibility_date = "2026-03-27"
workers_dev = false

[vars]
CDN_BASE_URL = "https://cdn.pkgs.ml"

[[routes]]
pattern = "registry.pkgs.ml"
custom_domain = true

[[r2_buckets]]
binding = "ML_PKGS_CDN"
bucket_name = "ml-pkgs-cdn"
preview_bucket_name = "ml-pkgs-cdn"

[[queues.producers]]
binding = "PACKAGE_PUBLISHED_QUEUE"
queue = "riot-package-published"
