[package]
name = "riot-model"
version = "0.0.32"
description = "Shared workspace, package, and build types"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_model.ml"

[dependencies]
std = "*"
ignore = "*"
serde = "*"
serde-json = "*"
