[package]
name = "typ"
version = "0.0.40"
description = "Incremental type checker engine for Riot"
license = "Apache-2.0"
public = true

[lib]
path = "src/typ.ml"

[dependencies]
std = { path = "../std", version = "*" }
syn = { path = "../syn", version = "*" }
contentstore = { path = "../contentstore", version = "*" }
serde = { path = "../serde", version = "*" }
