[package]
name = "riot-publish"
version = "0.0.43"
description = "Publish workflow orchestration"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_publish.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
pkgs-ml = { path = "../pkgs-ml", version = "*" }
riot-deps = { path = "../riot-deps", version = "*" }
riot-build = { path = "../riot-build", version = "*" }
riot-fix = { path = "../riot-fix", version = "*" }
riot-fmt = { path = "../riot-fmt", version = "*" }
