[package]
name = "testcontainers"
version = "0.0.39"
description = "Test-oriented Docker container lifecycle helpers"
license = "Apache-2.0"
public = true

[lib]
path = "src/testcontainers.ml"

[dependencies]
std = { path = "../std", version = "*" }
docker-client = { path = "../docker-client", version = "*" }
