open Std

(** gRPC Server Middleware

    Provides middleware for handling gRPC services in Suri web servers.
    Services are defined as first-class modules implementing service signatures
    generated by Grpc.Codegen.

    ## Example

    ```ocaml
    (* Implement a service *)
    module MyServiceImpl = struct
      let get_user request =
        Ok { id = request.user_id; name = "Alice" }
    end

    (* Use in middleware pipeline *)
    let app = Suri.Middleware.[
      Suri.Middleware.Router.middleware [
        Suri.GRPC.service "/myapp.MyService" (module MyServiceImpl : MyServiceSig);
      ]
    ]
    ```
*)

(** Create a gRPC service middleware

    Takes a service path prefix and a first-class module implementing the service.
    The module must match the service signature generated by Grpc.Codegen.

    Returns a middleware function that:
    - Matches requests to the service path
    - Decodes gRPC requests
    - Calls the appropriate service method
    - Encodes and sends gRPC responses

    @param path Service path prefix (e.g., "/myapp.UserService")
    @param impl First-class module implementing the service
    @return Middleware that handles gRPC calls to this service
*)
val service : string -> (module sig end) -> Middleware.Pipeline.middleware
