[package]
name = "hello-foreign"
version = "0.0.31"
description = "OCaml-to-Rust FFI smoke tests"
license = "Apache-2.0"

[lib]
path = "src/hello_foreign.ml"

[[bin]]
name = "hello"
path = "src/hello.ml"

[dependencies]
std = { path = "../std", version = "*" }

[foreign-dependencies.hello-rust]
path = "../../native/hello-rust"
build_cmd = ["cargo", "build", "--release"]
outputs = ["../../target/release/libhello_rust.a"]
