[package]
name = "tusk-publish"
version = "0.1.0"
description = "Publish command orchestration for Tusk."
license = "Apache-2.0"
public = true

[lib]
path = "src/tusk_publish.ml"

[dependencies]
std = { path = "../std" }
tusk-model = { path = "../tusk-model" }
pkgs-ml = { path = "../pkgs-ml" }
tusk-deps = { path = "../tusk-deps" }
tusk-build = { path = "../tusk-build" }
tusk-fix = { path = "../tusk-fix" }
tusk-fmt = { path = "../tusk-fmt" }
