[package]
name = "tusk-publish"
version = "0.0.1"
description = "Publish command orchestration for Tusk."
license = "Apache-2.0"
public = true

[lib]
path = "src/tusk_publish.ml"

[dependencies]
std = { path = "../std", version = "*" }
tusk-model = { path = "../tusk-model", version = "*" }
pkgs-ml = { path = "../pkgs-ml", version = "*" }
tusk-deps = { path = "../tusk-deps", version = "*" }
tusk-build = { path = "../tusk-build", version = "*" }
tusk-fix = { path = "../tusk-fix", version = "*" }
tusk-fmt = { path = "../tusk-fmt", version = "*" }
