[package]
name = "typ"
version = "0.0.36"
description = "Incremental type checker engine for Riot"
license = "Apache-2.0"
public = true

[lib]
path = "src/typ.ml"

[dependencies]
std = { path = "../../packages/std", version = "*" }
syn = { path = "../syn", version = "*" }
contentstore = { path = "../../packages/contentstore", version = "*" }
serde = { path = "../../packages/serde", version = "*" }
