[package]
name = "riot-lsp"
version = "0.0.35"
description = "Riot Language Server Protocol server"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_lsp.ml"

[dependencies]
jsonrpc = { path = "../jsonrpc", version = "*" }
krasny = { path = "../krasny", version = "*" }
lsp = { path = "../lsp", version = "*" }
riot-fix = { path = "../riot-fix", version = "*" }
riot-deps = { path = "../riot-deps", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
std = { path = "../std", version = "*" }
syn = { path = "../syn", version = "*" }
typ = { path = "../typ", version = "*" }
contentstore = { path = "../contentstore", version = "*" }
pkgs-ml = { path = "../pkgs-ml", version = "*" }
