[package]
name = "riot-toolchain"
version = "0.0.42"
description = "Compiler and toolchain invocation wrappers"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_toolchain.ml"

[dependencies]
std = "*"
riot-model = "*"
