[package]
name = "actors"
license = "Apache-2.0"
description = "The multicore actor runtime that powers Riot"
version = "0.0.16"
categories = ["runtime", "actors"]
keywords = ["actors", "scheduler", "mailbox"]
public = true

[riot.fix]
rules = [ "-no-stdlib" ]

[riot.fix.provider]
rules = [ "loop-yield" ]

[lib]
path = "src/actors.ml"

[dependencies]
kernel = { path = "../kernel", version = "*" }

[build-dependencies]
fixme = { path = "../fixme", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
std = { path = "../std", version = "*" }
