[package]
name = "pubgrub"
version = "0.0.36"
description = "PubGrub version solver"
license = "Apache-2.0"
public = true

[lib]
path = "src/Pubgrub.ml"

[dependencies]
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }

[[bin]]
name = "simple"
path = "examples/simple.ml"

[[bin]]
name = "solver_tests"
path = "tests/solver_tests.ml"

[[bin]]
name = "pubgrub_bench"
path = "bench/pubgrub_bench.ml"
