[package]
name = "pubgrub"
version = "0.1.0"
description = "PubGrub version solver for package dependency resolution."
license = "Apache-2.0"
public = true

[lib]
path = "src/pubgrub.ml"

[dependencies]
std = { path = "../std" }

[[bin]]
name = "simple"
path = "examples/simple.ml"

[[bin]]
name = "solver_tests"
path = "tests/solver_tests.ml"

