[package]
name = "pubgrub"
version = "0.1.0"

[dependencies]
std = { path = "../std" }

[[bin]]
name = "simple"
path = "examples/simple.ml"

[[bin]]
name = "solver_tests"
path = "tests/solver_tests.ml"


