[package]
name = "postgres"
version = "0.0.15"
description = "PostgreSQL adapter for sqlx"
license = "Apache-2.0"
public = true

[dependencies]
std = { path = "../std", version = "*" }
kernel = { path = "../kernel", version = "*" }
sqlx-driver = { path = "../sqlx-driver", version = "*" }
# Add dependencies here
