[package]
name = "postgres"
version = "0.0.38"
description = "PostgreSQL adapter for sqlx"
license = "Apache-2.0"
public = true

[dependencies]
std = "*"
kernel = "*"
sqlx-driver = "*"
serde = { path = "../serde", version = "*" }

[dev-dependencies]
dotenv = { path = "../dotenv", version = "*" }
propane = { path = "../propane", version = "*" }
testcontainers = { path = "../testcontainers", version = "*" }
