name = "riot-play-web"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-04-04"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false

[[routes]]
pattern = "play.riot.ml"
custom_domain = true

[assets]
binding = "ASSETS"
directory = "./dist/client"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
