(* Library interface module generated by riot *)

module Async = Async
module Archive = Archive
module Collections = Collections
module Compress = Compress
module Crypto = Crypto
module Env = Env
module Fd = Fd
module Fs = Fs
module IO = IO
module Iter = Iter
module Net = Net
module Option = Option
module Result = Result
module Sync = Sync
module System = System
module Terminal = Terminal
module Time = Time
module Types = Types
module UUID = Uuid
module Global = Global
module Effect = Effect
module Exception = Printexc
module Fun = Fun
module Float = Float
module Char = Char
module Bool = Bool
module Int = Int
module Int32 = Int32
module Int64 = Int64
module String = String
module Type = Type
module Uchar = Uchar
module Random = Random
module Regex = Regex
module Dynlink = Dynlink
module Ops = Ops
module Domain = Domain

(* Re-export global types and functions at top level for convenience *)

include Global

(* Convenient type aliases for collections *)

type 'a vec = 'a Collections.Vector.t

type 'a queue = 'a Collections.Queue.t

type 'a set = 'a Collections.HashSet.t

type ('k, 'v) map = ('k, 'v) Collections.HashMap.t

(* Constructor functions for collections *)

let vec = fun lst -> Collections.Vector.of_list lst

let queue = fun lst -> Collections.Queue.of_list lst

let set = fun lst -> Collections.HashSet.of_list lst

let map = fun lst -> Collections.HashMap.of_list lst

let stdout =
  let open IO in
    let module Write = struct
      type t = Fd.t

      type err = error

      let write = fun fd ~buf ->
        let bytes = Bytes.unsafe_of_string buf in
        let len = String.length buf in
        Fs.File.write fd ~pos:0 ~len bytes

      let write_owned_vectored = fun fd ~bufs ->
        Fs.File.write_vectored fd bufs

      let flush = fun _fd -> Ok ()
    end in
    Writer.of_write_src (module Write) stdout

external dangerous_unsafe_cast: 'a -> 'b = "%identity"
