[package]
name = "docker-client"
version = "0.0.41"
description = "Minimal Docker Engine API client for Riot"
license = "Apache-2.0"
public = true

[lib]
path = "src/docker_client.ml"

[dependencies]
std = { path = "../std", version = "*" }
blink = { path = "../blink", version = "*" }
serde = { path = "../serde", version = "*" }
serde-json = { path = "../serde-json", version = "*" }
