(* Library interface module generated by tusk *)
module Async = Async
module Crypto = Crypto
module Env = Env
module Fd = Fd
module Fs = Fs
module IO = IO
module Net = Net
module System = System
module Time = Time

(* Core types and modules for nostdlib packages *)
module Array = Array
module Atomic = Atomic
module Buffer = Buffer
module Bytes = Bytes
module Effect = Effect
module Exception = Printexc
module Fun = Fun
module Hashtbl = Hashtbl
module Int = Int
module Int32 = Int32
module Int64 = Int64
module List = List
module Obj = Obj
module Option = Option
module Queue = Queue
module Random = Random
module Seq = Seq
module String = String
module Type = Type
module Uchar = Uchar

(* Re-export global types and functions at top level for convenience *)
include module type of Global
