(* Library interface module generated by tusk *)
module Async = Async
module Collections = Collections
module Crypto = Crypto
module Env = Env
module Fd = Fd
module Fs = Fs
module IO = IO
module Iter = Iter
module Net = Net
module Option = Option
module Result = Result
module Sync = Sync
module System = System
module Time = Time

(* Core types and modules for nostdlib packages *)
module Effect = Effect
module Exception = Printexc
module Fun = Fun
module Int = Int
module Int32 = Int32
module Int64 = Int64
module String = String
module Type = Type
module Uchar = Uchar

(* Re-export global types and functions at top level for convenience *)
include module type of Global

(* Convenient type aliases for collections *)
type 'a vec = 'a Collections.Vector.t
type 'a queue = 'a Collections.Queue.t
type 'a set = 'a Collections.HashSet.t
type ('k, 'v) map = ('k, 'v) Collections.HashMap.t

(* Constructor functions for collections *)
val vec : 'a list -> 'a vec
val queue : 'a list -> 'a queue
val set : 'a list -> 'a set
val map : ('k * 'v) list -> ('k, 'v) map
