[package]
name = "riot-init"
version = "0.0.37"
description = "Workspace and package scaffolding"
license = "Apache-2.0"
public = false

[lib]
path = "src/riot_init.ml"

[dependencies]
std = { path = "../std", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
