open Std

type t =
  | WHITESPACE
  | COMMENT
  | DOCSTRING
  | IDENT
  | INT
  | FLOAT
  | STRING
  | CHAR
  | TRUE_KW
  | FALSE_KW
  | LET_KW
  | REC_KW
  | IN_KW
  | AND_KW
  | TYPE_KW
  | MODULE_KW
  | OPEN_KW
  | INCLUDE_KW
  | VAL_KW
  | EXTERNAL_KW
  | EXCEPTION_KW
  | IF_KW
  | THEN_KW
  | ELSE_KW
  | MATCH_KW
  | WITH_KW
  | FUN_KW
  | FUNCTION_KW
  | TRY_KW
  | WHEN_KW
  | OF_KW
  | STRUCT_KW
  | SIG_KW
  | END_KW
  | BEGIN_KW
  | ASSERT_KW
  | LAZY_KW
  | WHILE_KW
  | DO_KW
  | DONE_KW
  | FOR_KW
  | TO_KW
  | DOWNTO_KW
  | AS_KW
  | PRIVATE_KW
  | MUTABLE_KW
  | CONSTRAINT_KW
  | NONREC_KW
  | FUNCTOR_KW
  | CLASS_KW
  | OBJECT_KW
  | METHOD_KW
  | NEW_KW
  | VIRTUAL_KW
  | INHERIT_KW
  | INITIALIZER_KW
  | OPERATOR_KW
  | LPAREN
  | RPAREN
  | LBRACE
  | RBRACE
  | LBRACKET
  | RBRACKET
  | LBRACKET_BAR
  | BAR_RBRACKET
  | EQ
  | LT
  | GT
  | LTE
  | GTE
  | NE
  | PLUS
  | MINUS
  | STAR
  | SLASH
  | PERCENT
  | CARET
  | BANG
  | AMPAMP
  | BARBAR
  | COLON
  | SEMI
  | COMMA
  | DOT
  | DOTDOT
  | ARROW
  | LEFT_ARROW
  | FAT_ARROW
  | COLONCOLON
  | COLONEQ
  | QUESTION
  | AT
  | HASH
  | TILDE
  | DOLLAR
  | PIPE
  | AMPERSAND
  | UNDERSCORE
  | BACKTICK
  | QUOTE
  | STARSTAR
  | EQEQ
  | BANGEQ
  | ATAT
  | PIPEGT
  | PERCENTGT
  | LTPERCENT
  | PLUSDOT
  | MINUSDOT
  | STARDOT
  | SLASHDOT
  | EOF
  | UNKNOWN
  | SOURCE_FILE
  | IMPLEMENTATION
  | INTERFACE
  | STRUCTURE_ITEM
  | SIGNATURE_ITEM
  | LET_DECL
  | TYPE_DECL
  | MODULE_DECL
  | MODULE_TYPE_DECL
  | OPEN_DECL
  | INCLUDE_DECL
  | VAL_DECL
  | EXTERNAL_DECL
  | EXCEPTION_DECL
  | EXTENSION_ITEM
  | ATTRIBUTE_ITEM
  | EXPR_ITEM
  | LABELED_ARG
  | OPTIONAL_ARG
  | LABELED_PARAM
  | OPTIONAL_PARAM
  | OPTIONAL_PARAM_DEFAULT
  | LET_EXPR
  | LOCAL_OPEN_EXPR
  | LET_MODULE_EXPR
  | LET_EXCEPTION_EXPR
  | BINDING_OPERATOR_EXPR
  | FIRST_CLASS_MODULE_EXPR
  | EXTENSION_EXPR
  | UNREACHABLE_EXPR
  | LET_BINDING
  | IF_EXPR
  | MATCH_EXPR
  | MATCH_CASE
  | FUN_EXPR
  | FUNCTION_EXPR
  | TRY_EXPR
  | WHILE_EXPR
  | FOR_EXPR
  | ASSERT_EXPR
  | LAZY_EXPR
  | ATTRIBUTE_EXPR
  | SEQUENCE_EXPR
  | APPLY_EXPR
  | INFIX_EXPR
  | PREFIX_EXPR
  | ASSIGN_EXPR
  | FIELD_ACCESS_EXPR
  | METHOD_CALL_EXPR
  | POLY_VARIANT_EXPR
  | PATH_EXPR
  | LITERAL_EXPR
  | PAREN_EXPR
  | TUPLE_EXPR
  | LIST_EXPR
  | ARRAY_EXPR
  | RECORD_EXPR
  | RECORD_UPDATE_EXPR
  | ARRAY_INDEX_EXPR
  | STRING_INDEX_EXPR
  | TYPED_EXPR
  | PATTERN
  | WILDCARD_PATTERN
  | PATH_PATTERN
  | APPLY_PATTERN
  | LITERAL_PATTERN
  | PAREN_PATTERN
  | TUPLE_PATTERN
  | LIST_PATTERN
  | ARRAY_PATTERN
  | RECORD_PATTERN
  | POLY_VARIANT_PATTERN
  | LOCAL_OPEN_PATTERN
  | LOCALLY_ABSTRACT_TYPE_PATTERN
  | FIRST_CLASS_MODULE_PATTERN
  | INTERVAL_PATTERN
  | CONSTRAINT_PATTERN
  | ALIAS_PATTERN
  | OR_PATTERN
  | CONS_PATTERN
  | LAZY_PATTERN
  | EXCEPTION_PATTERN
  | TYPE_EXPR
  | ERROR
  | MISSING

let to_string = function
  | WHITESPACE -> "WHITESPACE"
  | COMMENT -> "COMMENT"
  | DOCSTRING -> "DOCSTRING"
  | IDENT -> "IDENT"
  | INT -> "INT"
  | FLOAT -> "FLOAT"
  | STRING -> "STRING"
  | CHAR -> "CHAR"
  | TRUE_KW -> "TRUE_KW"
  | FALSE_KW -> "FALSE_KW"
  | LET_KW -> "LET_KW"
  | REC_KW -> "REC_KW"
  | IN_KW -> "IN_KW"
  | AND_KW -> "AND_KW"
  | TYPE_KW -> "TYPE_KW"
  | MODULE_KW -> "MODULE_KW"
  | OPEN_KW -> "OPEN_KW"
  | INCLUDE_KW -> "INCLUDE_KW"
  | VAL_KW -> "VAL_KW"
  | EXTERNAL_KW -> "EXTERNAL_KW"
  | EXCEPTION_KW -> "EXCEPTION_KW"
  | IF_KW -> "IF_KW"
  | THEN_KW -> "THEN_KW"
  | ELSE_KW -> "ELSE_KW"
  | MATCH_KW -> "MATCH_KW"
  | WITH_KW -> "WITH_KW"
  | FUN_KW -> "FUN_KW"
  | FUNCTION_KW -> "FUNCTION_KW"
  | TRY_KW -> "TRY_KW"
  | WHEN_KW -> "WHEN_KW"
  | OF_KW -> "OF_KW"
  | STRUCT_KW -> "STRUCT_KW"
  | SIG_KW -> "SIG_KW"
  | END_KW -> "END_KW"
  | BEGIN_KW -> "BEGIN_KW"
  | ASSERT_KW -> "ASSERT_KW"
  | LAZY_KW -> "LAZY_KW"
  | WHILE_KW -> "WHILE_KW"
  | DO_KW -> "DO_KW"
  | DONE_KW -> "DONE_KW"
  | FOR_KW -> "FOR_KW"
  | TO_KW -> "TO_KW"
  | DOWNTO_KW -> "DOWNTO_KW"
  | AS_KW -> "AS_KW"
  | PRIVATE_KW -> "PRIVATE_KW"
  | MUTABLE_KW -> "MUTABLE_KW"
  | CONSTRAINT_KW -> "CONSTRAINT_KW"
  | NONREC_KW -> "NONREC_KW"
  | FUNCTOR_KW -> "FUNCTOR_KW"
  | CLASS_KW -> "CLASS_KW"
  | OBJECT_KW -> "OBJECT_KW"
  | METHOD_KW -> "METHOD_KW"
  | NEW_KW -> "NEW_KW"
  | VIRTUAL_KW -> "VIRTUAL_KW"
  | INHERIT_KW -> "INHERIT_KW"
  | INITIALIZER_KW -> "INITIALIZER_KW"
  | OPERATOR_KW -> "OPERATOR_KW"
  | LPAREN -> "LPAREN"
  | RPAREN -> "RPAREN"
  | LBRACE -> "LBRACE"
  | RBRACE -> "RBRACE"
  | LBRACKET -> "LBRACKET"
  | RBRACKET -> "RBRACKET"
  | LBRACKET_BAR -> "LBRACKET_BAR"
  | BAR_RBRACKET -> "BAR_RBRACKET"
  | EQ -> "EQ"
  | LT -> "LT"
  | GT -> "GT"
  | LTE -> "LTE"
  | GTE -> "GTE"
  | NE -> "NE"
  | PLUS -> "PLUS"
  | MINUS -> "MINUS"
  | STAR -> "STAR"
  | SLASH -> "SLASH"
  | PERCENT -> "PERCENT"
  | CARET -> "CARET"
  | BANG -> "BANG"
  | AMPAMP -> "AMPAMP"
  | BARBAR -> "BARBAR"
  | COLON -> "COLON"
  | SEMI -> "SEMI"
  | COMMA -> "COMMA"
  | DOT -> "DOT"
  | DOTDOT -> "DOTDOT"
  | ARROW -> "ARROW"
  | LEFT_ARROW -> "LEFT_ARROW"
  | FAT_ARROW -> "FAT_ARROW"
  | COLONCOLON -> "COLONCOLON"
  | COLONEQ -> "COLONEQ"
  | QUESTION -> "QUESTION"
  | AT -> "AT"
  | HASH -> "HASH"
  | TILDE -> "TILDE"
  | DOLLAR -> "DOLLAR"
  | PIPE -> "PIPE"
  | AMPERSAND -> "AMPERSAND"
  | UNDERSCORE -> "UNDERSCORE"
  | BACKTICK -> "BACKTICK"
  | QUOTE -> "QUOTE"
  | STARSTAR -> "STARSTAR"
  | EQEQ -> "EQEQ"
  | BANGEQ -> "BANGEQ"
  | ATAT -> "ATAT"
  | PIPEGT -> "PIPEGT"
  | PERCENTGT -> "PERCENTGT"
  | LTPERCENT -> "LTPERCENT"
  | PLUSDOT -> "PLUSDOT"
  | MINUSDOT -> "MINUSDOT"
  | STARDOT -> "STARDOT"
  | SLASHDOT -> "SLASHDOT"
  | EOF -> "EOF"
  | UNKNOWN -> "UNKNOWN"
  | SOURCE_FILE -> "SOURCE_FILE"
  | IMPLEMENTATION -> "IMPLEMENTATION"
  | INTERFACE -> "INTERFACE"
  | STRUCTURE_ITEM -> "STRUCTURE_ITEM"
  | SIGNATURE_ITEM -> "SIGNATURE_ITEM"
  | LET_DECL -> "LET_DECL"
  | TYPE_DECL -> "TYPE_DECL"
  | MODULE_DECL -> "MODULE_DECL"
  | MODULE_TYPE_DECL -> "MODULE_TYPE_DECL"
  | OPEN_DECL -> "OPEN_DECL"
  | INCLUDE_DECL -> "INCLUDE_DECL"
  | VAL_DECL -> "VAL_DECL"
  | EXTERNAL_DECL -> "EXTERNAL_DECL"
  | EXCEPTION_DECL -> "EXCEPTION_DECL"
  | EXTENSION_ITEM -> "EXTENSION_ITEM"
  | ATTRIBUTE_ITEM -> "ATTRIBUTE_ITEM"
  | EXPR_ITEM -> "EXPR_ITEM"
  | LABELED_ARG -> "LABELED_ARG"
  | OPTIONAL_ARG -> "OPTIONAL_ARG"
  | LABELED_PARAM -> "LABELED_PARAM"
  | OPTIONAL_PARAM -> "OPTIONAL_PARAM"
  | OPTIONAL_PARAM_DEFAULT -> "OPTIONAL_PARAM_DEFAULT"
  | LET_EXPR -> "LET_EXPR"
  | LOCAL_OPEN_EXPR -> "LOCAL_OPEN_EXPR"
  | LET_MODULE_EXPR -> "LET_MODULE_EXPR"
  | LET_EXCEPTION_EXPR -> "LET_EXCEPTION_EXPR"
  | BINDING_OPERATOR_EXPR -> "BINDING_OPERATOR_EXPR"
  | FIRST_CLASS_MODULE_EXPR -> "FIRST_CLASS_MODULE_EXPR"
  | EXTENSION_EXPR -> "EXTENSION_EXPR"
  | UNREACHABLE_EXPR -> "UNREACHABLE_EXPR"
  | LET_BINDING -> "LET_BINDING"
  | IF_EXPR -> "IF_EXPR"
  | MATCH_EXPR -> "MATCH_EXPR"
  | MATCH_CASE -> "MATCH_CASE"
  | FUN_EXPR -> "FUN_EXPR"
  | FUNCTION_EXPR -> "FUNCTION_EXPR"
  | TRY_EXPR -> "TRY_EXPR"
  | WHILE_EXPR -> "WHILE_EXPR"
  | FOR_EXPR -> "FOR_EXPR"
  | ASSERT_EXPR -> "ASSERT_EXPR"
  | LAZY_EXPR -> "LAZY_EXPR"
  | ATTRIBUTE_EXPR -> "ATTRIBUTE_EXPR"
  | SEQUENCE_EXPR -> "SEQUENCE_EXPR"
  | APPLY_EXPR -> "APPLY_EXPR"
  | INFIX_EXPR -> "INFIX_EXPR"
  | PREFIX_EXPR -> "PREFIX_EXPR"
  | ASSIGN_EXPR -> "ASSIGN_EXPR"
  | FIELD_ACCESS_EXPR -> "FIELD_ACCESS_EXPR"
  | METHOD_CALL_EXPR -> "METHOD_CALL_EXPR"
  | POLY_VARIANT_EXPR -> "POLY_VARIANT_EXPR"
  | PATH_EXPR -> "PATH_EXPR"
  | LITERAL_EXPR -> "LITERAL_EXPR"
  | PAREN_EXPR -> "PAREN_EXPR"
  | TUPLE_EXPR -> "TUPLE_EXPR"
  | LIST_EXPR -> "LIST_EXPR"
  | ARRAY_EXPR -> "ARRAY_EXPR"
  | RECORD_EXPR -> "RECORD_EXPR"
  | RECORD_UPDATE_EXPR -> "RECORD_UPDATE_EXPR"
  | ARRAY_INDEX_EXPR -> "ARRAY_INDEX_EXPR"
  | STRING_INDEX_EXPR -> "STRING_INDEX_EXPR"
  | TYPED_EXPR -> "TYPED_EXPR"
  | PATTERN -> "PATTERN"
  | WILDCARD_PATTERN -> "WILDCARD_PATTERN"
  | PATH_PATTERN -> "PATH_PATTERN"
  | APPLY_PATTERN -> "APPLY_PATTERN"
  | LITERAL_PATTERN -> "LITERAL_PATTERN"
  | PAREN_PATTERN -> "PAREN_PATTERN"
  | TUPLE_PATTERN -> "TUPLE_PATTERN"
  | LIST_PATTERN -> "LIST_PATTERN"
  | ARRAY_PATTERN -> "ARRAY_PATTERN"
  | RECORD_PATTERN -> "RECORD_PATTERN"
  | POLY_VARIANT_PATTERN -> "POLY_VARIANT_PATTERN"
  | LOCAL_OPEN_PATTERN -> "LOCAL_OPEN_PATTERN"
  | LOCALLY_ABSTRACT_TYPE_PATTERN -> "LOCALLY_ABSTRACT_TYPE_PATTERN"
  | FIRST_CLASS_MODULE_PATTERN -> "FIRST_CLASS_MODULE_PATTERN"
  | INTERVAL_PATTERN -> "INTERVAL_PATTERN"
  | CONSTRAINT_PATTERN -> "CONSTRAINT_PATTERN"
  | ALIAS_PATTERN -> "ALIAS_PATTERN"
  | OR_PATTERN -> "OR_PATTERN"
  | CONS_PATTERN -> "CONS_PATTERN"
  | LAZY_PATTERN -> "LAZY_PATTERN"
  | EXCEPTION_PATTERN -> "EXCEPTION_PATTERN"
  | TYPE_EXPR -> "TYPE_EXPR"
  | ERROR -> "ERROR"
  | MISSING -> "MISSING"

let is_trivia = function
  | WHITESPACE
  | COMMENT
  | DOCSTRING -> true
  | _ -> false

let is_token = function
  | SOURCE_FILE
  | IMPLEMENTATION
  | INTERFACE
  | STRUCTURE_ITEM
  | SIGNATURE_ITEM
  | LET_DECL
  | TYPE_DECL
  | MODULE_DECL
  | MODULE_TYPE_DECL
  | OPEN_DECL
  | INCLUDE_DECL
  | VAL_DECL
  | EXTERNAL_DECL
  | EXCEPTION_DECL
  | EXTENSION_ITEM
  | ATTRIBUTE_ITEM
  | EXPR_ITEM
  | LABELED_ARG
  | OPTIONAL_ARG
  | LABELED_PARAM
  | OPTIONAL_PARAM
  | OPTIONAL_PARAM_DEFAULT
  | LET_EXPR
  | LOCAL_OPEN_EXPR
  | LET_MODULE_EXPR
  | LET_EXCEPTION_EXPR
  | BINDING_OPERATOR_EXPR
  | FIRST_CLASS_MODULE_EXPR
  | EXTENSION_EXPR
  | UNREACHABLE_EXPR
  | LET_BINDING
  | IF_EXPR
  | MATCH_EXPR
  | MATCH_CASE
  | FUN_EXPR
  | FUNCTION_EXPR
  | TRY_EXPR
  | WHILE_EXPR
  | FOR_EXPR
  | ASSERT_EXPR
  | LAZY_EXPR
  | ATTRIBUTE_EXPR
  | SEQUENCE_EXPR
  | APPLY_EXPR
  | INFIX_EXPR
  | PREFIX_EXPR
  | ASSIGN_EXPR
  | FIELD_ACCESS_EXPR
  | METHOD_CALL_EXPR
  | POLY_VARIANT_EXPR
  | PATH_EXPR
  | LITERAL_EXPR
  | PAREN_EXPR
  | TUPLE_EXPR
  | LIST_EXPR
  | ARRAY_EXPR
  | RECORD_EXPR
  | RECORD_UPDATE_EXPR
  | ARRAY_INDEX_EXPR
  | STRING_INDEX_EXPR
  | TYPED_EXPR
  | PATTERN
  | WILDCARD_PATTERN
  | PATH_PATTERN
  | APPLY_PATTERN
  | LITERAL_PATTERN
  | PAREN_PATTERN
  | TUPLE_PATTERN
  | LIST_PATTERN
  | ARRAY_PATTERN
  | RECORD_PATTERN
  | POLY_VARIANT_PATTERN
  | LOCAL_OPEN_PATTERN
  | LOCALLY_ABSTRACT_TYPE_PATTERN
  | FIRST_CLASS_MODULE_PATTERN
  | INTERVAL_PATTERN
  | CONSTRAINT_PATTERN
  | ALIAS_PATTERN
  | OR_PATTERN
  | CONS_PATTERN
  | LAZY_PATTERN
  | EXCEPTION_PATTERN
  | TYPE_EXPR
  | ERROR
  | MISSING -> false
  | _ -> true

let is_node kind = not (is_token kind)
