open Std

(** OCaml syntax node kinds for Ceibo green trees *)
type t =
  (* Trivia *)
  | WHITESPACE
  | COMMENT
  | DOCSTRING
  (* Literals *)
  | INT_LITERAL
  | FLOAT_LITERAL
  | STRING_LITERAL
  | CHAR_LITERAL
  | BOOL_LITERAL
  | UNIT_LITERAL
  (* Expressions *)
  | IDENT_EXPR
  | PATH_EXPR
  | APPLY_EXPR
  | INFIX_EXPR
  | PREFIX_EXPR
  | IF_EXPR
  | MATCH_EXPR
  | FUN_EXPR
  | FUNCTION_EXPR
  | LET_EXPR
  | LET_REC_EXPR
  | SEQUENCE_EXPR
  | PAREN_EXPR
  | TUPLE_EXPR
  | LIST_EXPR
  | ARRAY_EXPR
  | RECORD_EXPR
  | RECORD_UPDATE_EXPR
  | FIELD_ACCESS_EXPR
  | CONSTRUCTOR_EXPR
  | ASSERT_EXPR
  | LAZY_EXPR
  | WHILE_EXPR
  | FOR_EXPR
  | TRY_EXPR
  | TYPED_EXPR
  | COERCE_EXPR
  (* Patterns *)
  | IDENT_PATTERN
  | WILDCARD_PATTERN
  | LITERAL_PATTERN
  | CONSTRUCTOR_PATTERN
  | TUPLE_PATTERN
  | LIST_PATTERN
  | ARRAY_PATTERN
  | CONS_PATTERN
  | RECORD_PATTERN
  | OR_PATTERN
  | AS_PATTERN
  | TYPED_PATTERN
  | LAZY_PATTERN
  | EXCEPTION_PATTERN
  | PAREN_PATTERN
  (* Top-level declarations *)
  | LET_BINDING
  | LET_REC_BINDING
  | TYPE_DECL
  | EXCEPTION_DECL
  | MODULE_DECL
  | MODULE_TYPE_DECL
  | OPEN_STMT
  | INCLUDE_STMT
  | EXTERNAL_DECL
  (* Structural *)
  | SOURCE_FILE
  | STRUCTURE
  | SIGNATURE
  | MATCH_CASE
  | PATTERN_GUARD
  | RECORD_FIELD
  | RECORD_FIELD_PATTERN
  | PARAMETER
  | ARGUMENT
  (* Error recovery *)
  | ERROR
  | MISSING

val to_string : t -> string
