[package]
name = "serde-urlencoded"
version = "0.0.32"

[lib]
path = "src/serde_urlencoded.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
