[package]
name = "miniriot"
version = "0.0.39"
description = "Bootstrap build tool for the Riot toolchain"
license = "Apache-2.0"
public = true

[riot.fix]
rules = [ 
  "-no-stdlib" 
]

[dependencies]
stdlib = "*"
unix = "*"
# Only needs standard library
