[package]
name = "miniriot"
license = "Apache-2.0"
description = "Actor-model multi-core runtime for OCaml 5"
public = true
version = "0.0.2"
categories = ["runtime", "actors"]
keywords = ["actors", "scheduler", "mailbox"]

[tusk.fix]
rules = [ "-no-stdlib" ]

[tusk.fix.provider]
rules = [ "loop-yield" ]

[lib]
path = "src/miniriot.ml"

[dependencies]
kernel = { path = "../kernel", version = "*" }

[build-dependencies]
fixme = { path = "../fixme", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
std = { path = "../std", version = "*" }
