(* Generated by raml-bindgen for example-lib *)

(* Functions *)

(** Create a new point *)
external point_new : int -> int -> unknown = "rust_point_new"


(** Get the x coordinate of a point *)
external point_x : unknown -> int = "rust_point_x"


(** Get the y coordinate of a point *)
external point_y : unknown -> int = "rust_point_y"


(** Calculate distance between two points *)
external point_distance : unknown -> unknown -> float = "rust_point_distance"


(** Free a point *)
external point_free : unknown -> unit = "rust_point_free"


(** Add two numbers *)
external add : int -> int -> int = "rust_add"


(** Multiply two numbers *)
external multiply : int -> int -> int = "rust_multiply"


(** Square a number *)
external square : int -> int = "rust_square"


