[package]
name = "registry"
version = "0.0.30"
description = "Package registry service for Riot"
license = "Apache-2.0"
public = true

[[bin]]
name = "registry"
path = "src/main.ml"

[dependencies]
std = "*"
# Add dependencies here
