[package]
name = "serde-cbor"
version = "0.0.37"
description = "CBOR support for the Serde serialization framework"
public = true
license = "Apache-2.0"

[lib]
path = "src/serde_cbor.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
