[package]
name = "serde-yaml"
version = "0.0.41"
description = "YAML support for the Serde serialization framework"
public = true
license = "Apache-2.0"

[lib]
path = "src/serde_yaml.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
