[package]
name = "serde-yaml"
version = "0.0.17"

[lib]
path = "src/serde_yaml.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*" }

[dev-dependencies]
propane = { path = "../propane", version = "*" }
