[package]
name = "serde-bin"
version = "0.0.31"

[lib]
path = "src/serde_bin.ml"

[dependencies]
serde = { path = "../serde", version = "*" }
std = { path = "../std", version = "*" }

[dev-dependencies]
stdlib = "*"
propane = { path = "../propane", version = "*" }
