(**
   Universally Unique Identifiers.

   128-bit universally unique identifiers implementing UUID versions 3, 4, 5,
   and 7 according to [RFC 9562](https://www.rfc-editor.org/rfc/rfc9562).

   ## Examples

   Generate random UUIDs:

   ```ocaml
   open Std

   (* Generate random UUID v4 *)
   let id = UUID.v4 () in
   println "%s" (UUID.to_string id)
   (* "550e8400-e29b-41d4-a716-446655440000" *)

   (* Generate timestamp-ordered UUID v7 (sortable) *)
   let db_id = UUID.v7 () in
   (* These sort by creation time! *)
   ```

   Parse and validate:

   ```ocaml
   match UUID.from_string "550e8400-e29b-41d4-a716-446655440000" with
   | Ok uuid ->
       UUID.version uuid  (* Some 4 *)
       UUID.is_nil uuid   (* false *)
   | Error (InvalidUuid msg) ->
       Log.error "Invalid UUID: %s" msg
   ```

   Name-based UUIDs (deterministic):

   ```ocaml
   (* Generate UUID from namespace and name *)
   let user_id = UUID.v5 ~namespace:UUID.ns_dns ~name:"user@example.com" in
   let same_id = UUID.v5 ~namespace:UUID.ns_dns ~name:"user@example.com" in
   UUID.equal user_id same_id  (* true - deterministic! *)
   ```

   Use in collections:

   ```ocaml
   let cache = Collections.HashMap.create () in
   Collections.HashMap.insert cache id "some data" |> ignore;

   let ids = Collections.HashSet.from_list [id1; id2; id3] in
   ```

   ## UUID Versions

   - **v4**: Random-based, most common for general use
   - **v7**: Timestamp + random, sortable, great for database keys
   - **v5**: Name-based with SHA-1, deterministic from namespace + name
   - **v3**: Name-based with MD5 (legacy, prefer v5)

   ## Use Cases

   - Database primary keys (use v7 for sortability)
   - Distributed system identifiers
   - API request/correlation IDs
   - Session tokens
   - Resource identifiers
*)
open Global

(** The type for UUIDs (128 bits / 16 bytes). *)
type t
type error =
  | InvalidUuid of string

(**
   Generates a random UUID v4.

   ## Examples

   ```ocaml
   let id = UUID.v4 () in
   UUID.version id  (* Some 4 *)
   ```

   ## ⚠️  Security Warning

   Uses OCaml's `Random.State` for generation, which is **NOT
   cryptographically secure**. While suitably random for most purposes
   (request IDs, non-security tokens), it is predictable by an observer.

   **Do not use for**:
   - Security tokens or session IDs
   - API keys
   - Password reset tokens
   - Any security-sensitive identifier

   For cryptographically secure UUIDs, use `v4_from_bytes` with bytes
   from a CSPRNG (to be added in future versions).
*)
val v4: unit -> t

(**
   Generates a timestamp-ordered UUID v7 (sortable).

   UUIDs generated by this function are sortable by creation time,
   making them ideal for database primary keys.

   ## Examples

   ```ocaml
   let id1 = UUID.v7 () in
   (* ... some time passes ... *)
   let id2 = UUID.v7 () in
   UUID.compare id1 id2  (* Negative - id1 < id2 *)
   ```

   ## Implementation

   Uses `Std.Time.SystemTime` for millisecond precision timestamps
   combined with random data.

   ## Note on Monotonicity

   This function does NOT guarantee monotonicity in the presence of system
   clock adjustments. If the system clock jumps backwards (NTP adjustment,
   manual change), a newly generated UUID may sort before a previously
   generated one.

   For transaction IDs or other use cases where strict monotonicity is
   required, use `v7_monotonic` instead.
*)
val v7: unit -> t

(**
   Generates a monotonically increasing UUID v7 safe for transaction IDs.

   This variant ensures that UUIDs are strictly monotonically increasing
   even in the presence of system clock adjustments (NTP, manual changes).

   ## When to Use

   - LSM transaction IDs where "last write wins" depends on ordering
   - Event sourcing where event order must be preserved
   - Any system where UUID ordering is semantically important

   ## Examples

   ```ocaml
   let tx_id1 = UUID.v7_monotonic () in
   let tx_id2 = UUID.v7_monotonic () in
   (* Guaranteed: UUID.compare tx_id1 tx_id2 < 0 *)
   ```

   ## Implementation

   Maintains global state tracking the last generated timestamp. If the
   system clock goes backwards, the timestamp is clamped to (last + 1ms)
   to preserve strict monotonicity.

   @since 1.0.0
*)
val v7_monotonic: unit -> t

(**
   Generates a name-based UUID v5 using SHA-1 hashing.

   Deterministic: same namespace and name always produce the same UUID.

   ## Examples

   ```ocaml
   let uuid = UUID.v5 ~namespace:UUID.ns_dns ~name:"example.com" in
   let same = UUID.v5 ~namespace:UUID.ns_dns ~name:"example.com" in
   UUID.equal uuid same  (* true *)
   ```

   ## Common Namespaces

   - `ns_dns`: For domain names
   - `ns_url`: For URLs
   - `ns_oid`: For ISO OIDs
   - `ns_x500`: For X.500 DNs
*)
val v5: namespace:t -> name:string -> t

(**
   Generates a name-based UUID v3 using MD5 hashing.

   Legacy version; prefer `v5` for new applications.

   ## Examples

   ```ocaml
   let uuid = UUID.v3 ~namespace:UUID.ns_url ~name:"https://example.com" in
   ```
*)
val v3: namespace:t -> name:string -> t

(**
   Creates a UUID v4 from 16 bytes of random data.

   The randomness is used literally in the result (except for version
   and variant bits).

   ## Examples

   ```ocaml
   let random_bytes = (* get 16 bytes from CSPRNG *) in
   let uuid = UUID.v4_from_bytes random_bytes in
   ```
*)
val v4_from_bytes: bytes -> t

(**
   Creates a UUID v7 from explicit timestamp and random parts.

   - `time_ms`: 48-bit millisecond POSIX timestamp
   - `rand_a`: 12-bit random value
   - `rand_b`: 62-bit random value

   ## Examples

   ```ocaml
   let now = Time.SystemTime.now () |> Time.SystemTime.to_millis in
   let uuid = UUID.v7_from_parts ~time_ms:now ~rand_a:0x123 ~rand_b:0xFFL in
   ```
*)
val v7_from_parts: time_ms:int64 -> rand_a:int -> rand_b:int64 -> t

(** The nil UUID (all zeros): [00000000-0000-0000-0000-000000000000]. *)
val nil: t

(** The max UUID (all ones): [ffffffff-ffff-ffff-ffff-ffffffffffff]. *)
val max: t

(** DNS namespace UUID for use with `v3` and `v5`. *)
val ns_dns: t

(** URL namespace UUID for use with `v3` and `v5`. *)
val ns_url: t

(** ISO OID namespace UUID for use with `v3` and `v5`. *)
val ns_oid: t

(** X.500 DN namespace UUID for use with `v3` and `v5`. *)
val ns_x500: t

(**
   Parses a UUID from string format.

   Accepts format: `"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"` where X is a
   hexadecimal digit (case-insensitive).

   ## Examples

   ```ocaml
   UUID.from_string "550e8400-e29b-41d4-a716-446655440000"
   (* Ok uuid *)

   UUID.from_string "550E8400-E29B-41D4-A716-446655440000"
   (* Ok uuid - uppercase works *)

   UUID.from_string "not-a-uuid"
   (* Error (InvalidUuid "...") *)
   ```
*)
val from_string: string -> (t, error) result

(**
   Creates a UUID from 16-byte binary representation.

   ## Examples

   ```ocaml
   let bytes = Bytes.create 16 in
   match UUID.from_bytes bytes with
   | Ok uuid -> ()
   | Error _ -> ()
   ```
*)
val from_bytes: bytes -> (t, error) result

(**
   Converts UUID to string format.

   Default: lowercase hexadecimal with dashes.

   ## Examples

   ```ocaml
   UUID.to_string uuid
   (* "550e8400-e29b-41d4-a716-446655440000" *)

   UUID.to_string ~upper:true uuid
   (* "550E8400-E29B-41D4-A716-446655440000" *)
   ```
*)
val to_string: ?upper:bool -> t -> string

(**
   Converts UUID to compact string format (no dashes).

   ## Examples

   ```ocaml
   UUID.to_string_nodash uuid
   (* "550e8400e29b41d4a716446655440000" *)
   ```
*)
val to_string_nodash: ?upper:bool -> t -> string

(** Converts UUID to 16-byte binary representation. *)
val to_bytes: t -> bytes

(**
   Tests if two UUIDs are equal.

   ## Examples

   ```ocaml
   UUID.equal uuid1 uuid2
   ```
*)
val equal: t -> t -> bool

(**
   Binary comparison of UUIDs.

   Returns negative if first < second, zero if equal, positive if first > second.

   ## Examples

   ```ocaml
   UUID.compare uuid1 uuid2
   ```
*)
val compare: t -> t -> Order.t

(**
   Tests if UUID is the nil UUID (all zeros).

   ## Examples

   ```ocaml
   UUID.is_nil UUID.nil  (* true *)
   UUID.is_nil (UUID.v4 ())  (* false *)
   ```
*)
val is_nil: t -> bool

(**
   Returns the UUID version (3, 4, 5, 7, 8) or `None` for nil/invalid.

   ## Examples

   ```ocaml
   UUID.version (UUID.v4 ())  (* Some 4 *)
   UUID.version UUID.nil  (* None *)
   ```
*)
val version: t -> int option

(** Returns the UUID variant field (typically 0x8-0xB for RFC 4122 UUIDs). *)
val variant: t -> int

(**
   Returns the creation timestamp for v7 UUIDs as a `Duration`.

   ## Examples

   ```ocaml
   let uuid = UUID.v7 () in
   match UUID.time uuid with
   | Some duration ->
       println "UUID created %s ago" (Time.Duration.to_string duration)
   | None ->
       (* not a v7 UUID *)
   ```
*)
val time: t -> Time.Duration.t option
